### ISSUE TITLE
Error when running demo.py

### ISSUE THREAD

**Issue by qinlihao** [facebookresearch/d2go#113]
Hi, I am a beginner in detectron2, and I have this error message when running demo.py 

AssertionError: Invalid type <class 'NoneType'> for key MODULES; valid types = {<class 'bool'>, <class 'tuple'>, <class 'int'>, <class 'list'>, <class 'str'>, <class 'float'>}

The full message: 
 python demo.py --config-file faster_rcnn_fbnetv3a_C4.yaml --input input1.jpg --output output1.jpg
[09/18 14:39:43 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='faster_rcnn_fbnetv3a_C4.yaml', input=['input1.jpg'], opts=[], output='output1.jpg', video_input=None, webcam=False)
Traceback (most recent call last):
  File "demo.py", line 156, in <module>
    main()
  File "demo.py", line 77, in main
    cfg = model_zoo.get_config(args.config_file)
  File "/home/lihao/anaconda3/envs/maskrcnn/lib/python3.6/site-packages/d2go/model_zoo/model_zoo.py", line 78, in get_config
    cfg = runner.get_default_cfg()
  File "/home/lihao/anaconda3/envs/maskrcnn/lib/python3.6/site-packages/d2go/runner/default_runner.py", line 700, in get_default_cfg
    _C = super(GeneralizedRCNNRunner, GeneralizedRCNNRunner).get_default_cfg()
  File "/home/lihao/anaconda3/envs/maskrcnn/lib/python3.6/site-packages/d2go/runner/default_runner.py", line 245, in get_default_cfg
    return get_default_cfg(_C)
  File "/home/lihao/anaconda3/envs/maskrcnn/lib/python3.6/site-packages/d2go/utils/get_default_cfg.py", line 53, in get_default_cfg
    add_quantization_default_configs(_C)
  File "/home/lihao/anaconda3/envs/maskrcnn/lib/python3.6/site-packages/d2go/modeling/quantization.py", line 82, in add_quantization_default_configs
    _C.QUANTIZATION.MODULES = None
  File "/home/lihao/anaconda3/envs/maskrcnn/lib/python3.6/site-packages/fvcore/common/config.py", line 148, in __setattr__
    super().__setattr__(name, val)
  File "/home/lihao/anaconda3/envs/maskrcnn/lib/python3.6/site-packages/yacs/config.py", line 158, in __setattr__
    type(value), name, _VALID_TYPES
  File "/home/lihao/anaconda3/envs/maskrcnn/lib/python3.6/site-packages/yacs/config.py", line 521, in _assert_with_logging
    assert cond, msg
AssertionError: Invalid type <class 'NoneType'> for key MODULES; valid types = {<class 'bool'>, <class 'tuple'>, <class 'int'>, <class 'list'>, <class 'str'>, <class 'float'>}

Can anyone help me to figure out the reason? Any help would be appreciated. Thank you in advance.

**Comment by wat3rBro** [comment]
Could you try changing https://github.com/facebookresearch/d2go/blob/main/d2go/modeling/quantization.py#L82 to `[]` instead of `None`.
