### ISSUE TITLE
.pt file not working in mobile device but its working fine in my system

### ISSUE THREAD

**Issue by ashutoshsoni891** [facebookresearch/d2go#125]
following snippet is working for me :

```
import torch , torchvision
model = torch.jit.load('model.pt')
out = model(torch,randn(3,320,224))
print(out ) # length is 6, i.e bbox , class , keypoints , heatmaps , confidence , shape
```
but when I run in mobile device , I am getting error 
```
2021-10-08 15:43:23.940 3305-3305/ai.mysystem.myapplication E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ai.mysystem.myapplication, PID: 3305
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=72, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:15784 flg=0x1 }} to activity {ai.mysystem.myapplication/ai.mysystem.myapplication.MainActivity}: java.lang.RuntimeException: The following operation failed in the TorchScript interpreter.
    Traceback of TorchScript, serialized code (most recent call last):
      File "code/__torch__/detectron2/export/flatten.py", line 9, in forward
      def forward(self: __torch__.detectron2.export.flatten.TracingAdapter,
        argument_1: Tensor) -> Tuple[Tensor, Tensor, Tensor, Tensor, Tensor, Tensor]:
        0, 1, 2, 3, 4, 5, = (self.model).forward(argument_1, )
                                   ~~~~~~~~~~~~~~~~~~~ <--- HERE
        return (0, 1, 2, 3, 4, 5)
      File "code/__torch__/detectron2/export/flatten/___torch_mangle_10409.py", line 9, in forward
      def forward(self: __torch__.detectron2.export.flatten.___torch_mangle_10409.TracingAdapter,
        argument_1: Tensor) -> Tuple[Tensor, Tensor, Tensor, Tensor, Tensor, Tensor]:
        0, 1, 2, 3, 4, 5, = (self.model).forward(argument_1, )
                                   ~~~~~~~~~~~~~~~~~~~ <--- HERE
        return (0, 1, 2, 3, 4, 5)
      File "code/__torch__/d2go/utils/export_utils/___torch_mangle_10408.py", line 27, in forward
        X = torch.contiguous(batched_imgs)
        12 = (2).forward(X, )
        13 = (0).forward(_12, (_1).forward(_12, image_size, ), image_size, )
               ~~~~~~~~~~~ <--- HERE
        14, 15, 16, 17, 18, = 13
        19 = (14, 15, 16, 17, 18, image_size)
      File "code/__torch__/detectron2/modeling/roi_heads/roi_heads/___torch_mangle_10406.py", line 130, in forward
        _67 = torch.slice(filter_inds0, 0, 0, 9223372036854775807)
        _68 = torch.select(_67, 1, 1)
        69 = (1).forward((_2).forward(argument_1, tensor2, ), tensor2, )
               ~~~~~~~~~~~ <--- HERE
        70, 71, = _69
        return (tensor2, 68, 70, 71, 65)
      File "code/__torch__/mobile_cv/arch/utils/quantize_utils/___torch_mangle_10405.py", line 20, in forward
        5 = (1).forward((_2).forward((_3).forward(_4, ), ), )
        _6 = torch.detach(_5)
        keypoint_results = _0(_6, torch.detach(tensor), )
                           ~~ <--- HERE
        _7 = ops.prim.NumToTensor(torch.size(tensor, 0))
        _8 = int(_7)
      File "code/__torch__/detectron2/structures/keypoints.py", line 16, in heatmaps_to_keypoints
      widths_ceil = torch.ceil(widths)
      heights_ceil = torch.ceil(heights)
      _5 = torch.slice(torch.size(maps0), None, 2)
           ~~~~~~~~~~~ <--- HERE
      num_rois, num_keypoints, = _5
      _6 = [(torch.size(rois0))[0], num_keypoints, 4]
    
    Traceback of TorchScript, original code (most recent call last):
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/detectron2/structures/keypoints.py", line 206, in heatmaps_to_keypoints
        heights_ceil = heights.ceil()
    
        num_rois, num_keypoints = maps.shape[:2]
                                  ~~~~~~~~~~~~~~ <--- HERE
        xy_preds = maps.new_zeros(rois.shape[0], num_keypoints, 4)
    RuntimeError: isInt() INTERNAL ASSERT FAILED at "../../../../src/main/cpp/libtorch_include/arm64-v8a/ATen/core/ivalue.h":503, please report a bug to PyTorch. 
    
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5098)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5139)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2104)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:7861)
2021-10-08 15:43:23.940 3305-3305/ai.mysystem.myapplication E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
     Caused by: java.lang.RuntimeException: The following operation failed in the TorchScript interpreter.
    Traceback of TorchScript, serialized code (most recent call last):
      File "code/__torch__/detectron2/export/flatten.py", line 9, in forward
      def forward(self: __torch__.detectron2.export.flatten.TracingAdapter,
        argument_1: Tensor) -> Tuple[Tensor, Tensor, Tensor, Tensor, Tensor, Tensor]:
        0, 1, 2, 3, 4, 5, = (self.model).forward(argument_1, )
                                   ~~~~~~~~~~~~~~~~~~~ <--- HERE
        return (0, 1, 2, 3, 4, 5)
      File "code/__torch__/detectron2/export/flatten/___torch_mangle_10409.py", line 9, in forward
      def forward(self: __torch__.detectron2.export.flatten.___torch_mangle_10409.TracingAdapter,
        argument_1: Tensor) -> Tuple[Tensor, Tensor, Tensor, Tensor, Tensor, Tensor]:
        0, 1, 2, 3, 4, 5, = (self.model).forward(argument_1, )
                                   ~~~~~~~~~~~~~~~~~~~ <--- HERE
        return (0, 1, 2, 3, 4, 5)
      File "code/__torch__/d2go/utils/export_utils/___torch_mangle_10408.py", line 27, in forward
        X = torch.contiguous(batched_imgs)
        12 = (2).forward(X, )
        13 = (0).forward(_12, (_1).forward(_12, image_size, ), image_size, )
               ~~~~~~~~~~~ <--- HERE
        14, 15, 16, 17, 18, = 13
        19 = (14, 15, 16, 17, 18, image_size)
      File "code/__torch__/detectron2/modeling/roi_heads/roi_heads/___torch_mangle_10406.py", line 130, in forward
        _67 = torch.slice(filter_inds0, 0, 0, 9223372036854775807)
        _68 = torch.select(_67, 1, 1)
        69 = (1).forward((_2).forward(argument_1, tensor2, ), tensor2, )
               ~~~~~~~~~~~ <--- HERE
        70, 71, = _69
        return (tensor2, 68, 70, 71, 65)
      File "code/__torch__/mobile_cv/arch/utils/quantize_utils/___torch_mangle_10405.py", line 20, in forward
        5 = (1).forward((_2).forward((_3).forward(_4, ), ), )
        _6 = torch.detach(_5)
        keypoint_results = _0(_6, torch.detach(tensor), )
                           ~~ <--- HERE
        _7 = ops.prim.NumToTensor(torch.size(tensor, 0))
        _8 = int(_7)
      File "code/__torch__/detectron2/structures/keypoints.py", line 16, in heatmaps_to_keypoints
      widths_ceil = torch.ceil(widths)
      heights_ceil = torch.ceil(heights)
      _5 = torch.slice(torch.size(maps0), None, 2)
           ~~~~~~~~~~~ <--- HERE
      num_rois, num_keypoints, = _5
      _6 = [(torch.size(rois0))[0], num_keypoints, 4]
    
    Traceback of TorchScript, original code (most recent call last):
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/detectron2/structures/keypoints.py", line 206, in heatmaps_to_keypoints
        heights_ceil = heights.ceil()
    
        num_rois, num_keypoints = maps.shape[:2]
                                  ~~~~~~~~~~~~~~ <--- HERE
        xy_preds = maps.new_zeros(rois.shape[0], num_keypoints, 4)
    RuntimeError: isInt() INTERNAL ASSERT FAILED at "../../../../src/main/cpp/libtorch_include/arm64-v8a/ATen/core/ivalue.h":503, please report a bug to PyTorch. 
    
        at org.pytorch.NativePeer.forward(Native Method)
        at org.pytorch.Module.forward(Module.java:49)
        at ai.mysystem.myapplication.MainActivity.runInference(MainActivity.java:141)
        at ai.mysystem.myapplication.MainActivity.onActivityResult(MainActivity.java:114)
        at android.app.Activity.dispatchActivityResult(Activity.java:8476)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5091)
        	... 11 more
2021-10-08 15:43:24.002 3305-3305/ai.mysystem.myapplication I/Process: Sending signal. PID: 3305 SIG: 9
```

**Comment by ashutoshsoni891** [comment]
the model was trained on pytorch 1.9 and android app has 1.8 , is this the issue ?
Also when I am loading the model to device with pytorch 1.8 , I am getting this error :

```
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/detectron2/structures/keypoints.py", line 206, in heatmaps_to_keypoints
    heights_ceil = heights.ceil()

    num_rois, num_keypoints = maps.shape[:2]
                              ~~~~~~~~~~~~~~ <--- HERE
    xy_preds = maps.new_zeros(rois.shape[0], num_keypoints, 4)
RuntimeError: isInt() INTERNAL ASSERT FAILED at "/pytorch/aten/src/ATen/core/ivalue.h":503, please report a bug to PyTorch. 
```

**Comment by dipu0** [comment]
did you find any solution??
