### ISSUE TITLE
 No module named 'torch.ao.quantization.quantize_fx'

### ISSUE THREAD

**Issue by cloveropen** [facebookresearch/d2go#136]
## Instructions To Reproduce the 🐛 Bug:
1. Full runnable code or full changes you made:
```
python demo.py --config-file faster_rcnn_fbnetv3a_C4.yaml --input input.jpg --output output.jpg
```

3. __Full logs__ or other relevant observations:
```
$ python demo.py --config-file faster_rcnn_fbnetv3a_C4.yaml --input input.jpg --output output.jpg
Traceback (most recent call last):
  File "demo.py", line 11, in <module>
    from d2go.model_zoo import model_zoo
  File "/home/d2go/dtgovenv/lib/python3.8/site-packages/d2go/model_zoo/model_zoo.py", line 7, in <module>
    from d2go.runner import create_runner
  File "/home/d2go/dtgovenv/lib/python3.8/site-packages/d2go/runner/__init__.py", line 10, in <module>
    from .default_runner import BaseRunner, Detectron2GoRunner, GeneralizedRCNNRunner
  File "/home/d2go/dtgovenv/lib/python3.8/site-packages/d2go/runner/default_runner.py", line 28, in <module>
    from d2go.export.d2_meta_arch import patch_d2_meta_arch
  File "/home/d2go/dtgovenv/lib/python3.8/site-packages/d2go/export/__init__.py", line 5, in <module>
    from . import torchscript  # noqa
  File "/home/d2go/dtgovenv/lib/python3.8/site-packages/d2go/export/torchscript.py", line 11, in <module>
    from d2go.export.api import ModelExportMethodRegistry, ModelExportMethod
  File "/home/d2go/dtgovenv/lib/python3.8/site-packages/d2go/export/api.py", line 56, in <module>
    from torch.ao.quantization.quantize_fx import convert_fx
ModuleNotFoundError: No module named 'torch.ao.quantization.quantize_fx'
```
4. please simplify the steps as much as possible so they do not require additional resources to run, such as a private dataset.
os:ubuntu20.04
pytorch1.10
cuda 11.3

**Comment by savanovich** [comment]
Pytorch nightly has to be used as the stable version doesn't have such functionality
https://github.com/pytorch/pytorch/blob/master/torch/ao/quantization/quantize_fx.py
https://github.com/pytorch/pytorch/tree/v1.10.0/torch/ao/quantization

**Comment by zhanghang1989** [comment]
Yes, please use the nightly version for now.

**Comment by cloveropen** [comment]
now i install pytorch nightly,use cuda 10.1.run the demo again:
 python demo.py --config-file faster_rcnn_fbnetv3a_C4.yaml --input input.jpg --output output.jpg
get the error:
Traceback (most recent call last):
  File "demo.py", line 11, in <module>
    from d2go.model_zoo import model_zoo
  File "/home/cloveropen/docker/venv/lib/python3.8/site-packages/d2go/model_zoo/model_zoo.py", line 7, in <module>
    from d2go.runner import create_runner
  File "/home/cloveropen/docker/venv/lib/python3.8/site-packages/d2go/runner/__init__.py", line 10, in <module>
    from .default_runner import BaseRunner, Detectron2GoRunner, GeneralizedRCNNRunner
  File "/home/cloveropen/docker/venv/lib/python3.8/site-packages/d2go/runner/default_runner.py", line 28, in <module>
    from d2go.export.d2_meta_arch import patch_d2_meta_arch
  File "/home/cloveropen/docker/venv/lib/python3.8/site-packages/d2go/export/__init__.py", line 5, in <module>
    from . import torchscript  # noqa
  File "/home/cloveropen/docker/venv/lib/python3.8/site-packages/d2go/export/torchscript.py", line 13, in <module>
    from detectron2.export.flatten import TracingAdapter, flatten_to_tuple
  File "/home/cloveropen/docker/venv/lib/python3.8/site-packages/detectron2/export/__init__.py", line 3, in <module>
    from .api import *
  File "/home/cloveropen/docker/venv/lib/python3.8/site-packages/detectron2/export/api.py", line 6, in <module>
    from caffe2.proto import caffe2_pb2
  File "/home/cloveropen/docker/venv/lib/python3.8/site-packages/caffe2/proto/__init__.py", line 11, in <module>
    from caffe2.proto import caffe2_pb2, metanet_pb2, torch_pb2
ImportError: cannot import name 'metanet_pb2' from partially initialized module 'caffe2.proto' (most likely due to a circular import) (/home/cloveropen/docker/venv/lib/python3.8/site-packages/caffe2/proto/__init__.py)

**Comment by cloveropen** [comment]
solved,thanks all!
