### ISSUE TITLE
exporting faster_rcnn_fbnetv3g_fpn get a NotImplementedError: Could not run 'aten::_slow_conv2d_forward' with arguments from the 'QuantizedCPU' backend

### ISSUE THREAD

**Issue by LP308210365** [facebookresearch/d2go#159]
## I used the demo to train and export  faster_rcnn_fbnetv3g_fpn model using customized COCO datasets, got this error, all the other detection models works, code and error logs is as follows:
```
import os
import cv2
from detectron2.data.datasets import register_coco_instances
from detectron2.data import MetadataCatalog, DatasetCatalog
from detectron2.utils.visualizer import Visualizer, ColorMode
from d2go.model_zoo import model_zoo
import matplotlib.pyplot as plt
import copy
from detectron2.data import build_detection_test_loader
from d2go.export.api import convert_and_export_predictor
from d2go.utils.testing.data_loader_helper import create_fake_detection_data_loader
from d2go.export.d2_meta_arch import patch_d2_meta_arch
from mobile_cv.predictor.api import create_predictor
import logging
from d2go.utils.demo_predictor import DemoPredictor
from d2go.runner import GeneralizedRCNNRunner

register_coco_instances("my_dataset_train", {}, "/home/liupeng/sdb1/Image/ScaleDetection/Train/humanDetec/V4/Annotations/coco_info.json",
                        "/home/liupeng/sdb1/Image/ScaleDetection/Train/humanDetec/V4/AugImages")

model_name = "faster_rcnn_fbnetv3g_fpn.yaml"

def prepare_for_launch():
    runner = GeneralizedRCNNRunner()
    cfg = runner.get_default_cfg()
    cfg.merge_from_file(model_zoo.get_config_file(model_name))
    cfg.MODEL_EMA.ENABLED = False
    cfg.DATASETS.TRAIN = ("my_dataset_train",)
    cfg.DATASETS.TEST = ("my_dataset_train",)
    cfg.DATALOADER.NUM_WORKERS = 2
    cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url(model_name)  # Let training initialize from model zoo
    cfg.SOLVER.IMS_PER_BATCH = 1
    cfg.SOLVER.BASE_LR = 0.00025  # pick a good LR
    cfg.SOLVER.MAX_ITER = 1    # 600 iterations seems good enough for this toy dataset; you will need to train longer for a practical dataset
    cfg.SOLVER.STEPS = []        # do not decay learning rate
    cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128   # faster, and good enough for this toy dataset (default: 512)
    cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1  # only has one class (ballon). (see https://detectron2.readthedocs.io/tutorials/datasets.html#update-the-config-for-new-datasets)
    # NOTE: this config means the number of classes, but a few popular unofficial tutorials incorrect uses num_classes+1 here.
    os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
    return cfg, runner

cfg, runner = prepare_for_launch()
model = runner.build_model(cfg)
runner.do_train(cfg, model, resume=False)

# # disable all the warnings
previous_level = logging.root.manager.disable
logging.disable(logging.INFO)

patch_d2_meta_arch()

cfg_name = model_name
pytorch_model = model_zoo.get(cfg_name, trained=True)
pytorch_model.cpu()

with create_fake_detection_data_loader(224, 320, is_train=False) as data_loader:
    predictor_path = convert_and_export_predictor(
            model_zoo.get_config(cfg_name),
            copy.deepcopy(pytorch_model),
            "torchscript_int8@tracing",
            './',
            data_loader,
        )

# recover the logging level
logging.disable(previous_level)

model = create_predictor(predictor_path)

im = cv2.imread("/home/liupeng/sdb1/PythonProject/scaleDetection/data/images/12_20_09_24_087.jpg")
predictor = DemoPredictor(model)
outputs = predictor(im)
v = Visualizer(im,
                    MetadataCatalog.get("my_dataset_train"),
                    scale=1,
                    instance_mode=ColorMode.IMAGE
                    )
out = v.draw_instance_predictions(outputs["instances"].to("cpu"))
plt.imshow(out.get_image()[:, :, ::-1])
plt.show()

```
Traceback (most recent call last):
  File "/home/liupeng/sdb1/PythonProject/scaleDetection/detectron2go/fasterrcnn/train.py", line 114, in <module>
  File "/home/liupeng/anaconda3/envs/scaleDetection/lib/python3.9/site-packages/d2go/export/api.py", line 151, in convert_and_export_predictor
    return export_predictor(cfg, pytorch_model, predictor_type, output_dir, data_loader)
  File "/home/liupeng/anaconda3/envs/scaleDetection/lib/python3.9/site-packages/d2go/export/api.py", line 174, in export_predictor
    return default_export_predictor(
  File "/home/liupeng/anaconda3/envs/scaleDetection/lib/python3.9/site-packages/d2go/export/api.py", line 262, in default_export_predictor
    model_info = _export_single_model(
  File "/home/liupeng/anaconda3/envs/scaleDetection/lib/python3.9/site-packages/d2go/export/api.py", line 196, in _export_single_model
    load_kwargs = model_export_method.export(
  File "/home/liupeng/anaconda3/envs/scaleDetection/lib/python3.9/site-packages/d2go/export/torchscript.py", line 348, in new_f
    return old_f(cls, model, input_args, save_path, export_method, **export_kwargs)
  File "/home/liupeng/anaconda3/envs/scaleDetection/lib/python3.9/site-packages/d2go/export/torchscript.py", line 209, in new_f
    outputs = model(*input_args)
  File "/home/liupeng/anaconda3/envs/scaleDetection/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/liupeng/anaconda3/envs/scaleDetection/lib/python3.9/site-packages/d2go/modeling/meta_arch/rcnn.py", line 388, in forward
    return self.model.inference(inputs, do_postprocess=False)[0]
  File "/home/liupeng/anaconda3/envs/scaleDetection/lib/python3.9/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 200, in inference
    features = self.backbone(images.tensor)
  File "/home/liupeng/anaconda3/envs/scaleDetection/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/liupeng/anaconda3/envs/scaleDetection/lib/python3.9/site-packages/mobile_cv/arch/utils/quantize_utils.py", line 345, in wrapped_method
    q_outputs = getattr(ModuleType, wrapped_method_name)(self, *q_args, **q_kwargs)
  File "/home/liupeng/anaconda3/envs/scaleDetection/lib/python3.9/site-packages/detectron2/modeling/backbone/fpn.py", line 128, in forward
    prev_features = self.lateral_convs[0](bottom_up_features[self.in_features[-1]])
  File "/home/liupeng/anaconda3/envs/scaleDetection/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/liupeng/anaconda3/envs/scaleDetection/lib/python3.9/site-packages/detectron2/layers/wrappers.py", line 106, in forward
    x = F.conv2d(
NotImplementedError: Could not run 'aten::_slow_conv2d_forward' with arguments from the 'QuantizedCPU' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::_slow_conv2d_forward' is only available for these backends: [CPU, CUDA, BackendSelect, Python, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradLazy, AutogradXPU, AutogradMLC, AutogradHPU, AutogradNestedTensor, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, UNKNOWN_TENSOR_TYPE_ID, Autocast, Batched, VmapMode, Functionalize].

## Expected behavior:

is it a config error?

**Comment by zhanghang1989** [comment]
Please change the  https://github.com/facebookresearch/d2go/blob/main/configs/faster_rcnn_fbnetv3g_fpn.yaml#L38
to "MaskRCNNConvUpsampleHead"

**Comment by LP308210365** [comment]
> Please change the https://github.com/facebookresearch/d2go/blob/main/configs/faster_rcnn_fbnetv3g_fpn.yaml#L38 to "MaskRCNNConvUpsampleHead"

I changed the config to"MaskRCNNConvUpsampleHead", and i have used the latest master branch, but this error still exits.

**Comment by cloveropen** [comment]
and mask_rcnn_fbnetv3g_fpn.yaml have the same error

**Comment by zhanghang1989** [comment]
@wat3rBro Any thoughts about this issue? Is that because of using `FBNetV2FpnBackbone`

**Comment by wat3rBro** [comment]
> @wat3rBro Any thoughts about this issue? Is that because of using `FBNetV2FpnBackbone`

@zhanghang1989 yes, it looks like issue from FPN, https://github.com/facebookresearch/d2go/pull/163 should fix it.

**Comment by cloveropen** [comment]
when update to the new version,I can create a pt file.but when use it in android-demo-app\d2go,both the mask_rcnn_fbnetv3g_fpn.yaml and  faster_rcnn_fbnetv3g_fpn.yaml get the error:

'''
E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: org.pytorch.demo.objectdetection, PID: 19522
    java.lang.RuntimeException: The following operation failed in the TorchScript interpreter.
    Traceback of TorchScript, serialized code (most recent call last):
      File "code/__torch__.py", line 16, in forward
        x0 = _0(x, None, scale, "bilinear", True, True, False, )
        model = self.model
        out = (model).forward(torch.select(x0, 0, 0), )
               ~~~~~~~~~~~~~~ <--- HERE
        res = annotate(Dict[str, Tensor], {})
        torch._set_item(res, "boxes", torch.div((out)[0], scale))
      File "code/__torch__/detectron2/export/flatten.py", line 10, in forward
        argument_1: Tensor) -> Tuple[Tensor, Tensor, Tensor, Tensor]:
        model = self.model
        _0, _1, _2, _3, = (model).forward(argument_1, )
                           ~~~~~~~~~~~~~~ <--- HERE
        return (_0, _1, _2, _3)
      File "code/__torch__/d2go/modeling/meta_arch/rcnn.py", line 34, in forward
        X = torch.contiguous(batched_imgs)
        _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, = (backbone).forward(X, )
        _18 = (proposal_generator).forward(_8, _9, _10, _11, _12, _13, _14, _15, _16, image_size, )
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        _19 = (roi_heads).forward(_9, _18, _10, _17, _15, image_size, )
        _20, _21, _22, = _19
      File "code/__torch__/detectron2/modeling/proposal_generator/rpn.py", line 24, in forward
        _1 = (anchor_generator).forward(argument_1, argument_2, argument_3, argument_4, argument_5, argument_6, argument_7, argument_8, )
        _2, _3, _4, _5, _6, = _1
        _7 = (rpn_head).forward(argument_1, argument_2, argument_3, argument_9, argument_8, )
              ~~~~~~~~~~~~~~~~~ <--- HERE
        _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, = _7
        logits_i = torch.flatten(torch.permute(_8, [0, 2, 3, 1]), 1)
      File "code/__torch__/mobile_cv/arch/utils/quantize_utils/___torch_mangle_748.py", line 22, in forward
        _0 = (quant_stubs).forward(argument_1, argument_2, argument_3, argument_4, argument_5, )
        _1, _2, _3, _4, _5, = _0
        _6 = (rpn_regressor).forward((rpn_feature).forward(_1, ), (rpn_feature).forward1(_2, ), (rpn_feature).forward2(_3, ), (rpn_feature).forward3(_4, ), (rpn_feature).forward4(_5, ), )
                                                                   ~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, = _6
        _17 = (dequant_stubs).forward(_7, _8, _9, _10, _11, _12, _13, _14, _15, _16, )
      File "code/__torch__/d2go/modeling/backbone/fbnet_v2.py", line 54, in forward1
        argument_1: Tensor) -> Tensor:
        _0 = getattr(self, "0")
        return (_0).forward1(argument_1, )
                ~~~~~~~~~~~~ <--- HERE
      def forward2(self: __torch__.d2go.modeling.backbone.fbnet_v2.FBNetModule,
        argument_1: Tensor) -> Tensor:
      File "code/__torch__/torch/nn/modules/container/___torch_mangle_726.py", line 14, in forward1
        argument_1: Tensor) -> Tensor:
        fbnetv2_0_0 = self.fbnetv2_0_0
        _0 = (fbnetv2_0_0).forward1(argument_1, )
              ~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        return _0
      def forward2(self: __torch__.torch.nn.modules.container.___torch_mangle_726.Sequential,
      File "code/__torch__/mobile_cv/arch/fbnet_v2/irf_block/___torch_mangle_725.py", line 24, in forward1
        dw = self.dw
        pw = self.pw
        _1 = (dw).forward1((pw).forward1(argument_1, ), )
                            ~~~~~~~~~~~~ <--- HERE
        _2 = (pwl).forward1((se).forward1(_1, ), )
        return _2
      File "code/__torch__/mobile_cv/arch/fbnet_v2/basic_blocks/___torch_mangle_708.py", line 23, in forward1
        bn = self.bn
        conv = self.conv
        _3 = (conv).forward1(argument_1, )
              ~~~~~~~~~~~~~~ <--- HERE
        _4 = (bn).forward1()
        _5 = (relu).forward1()
      File "code/__torch__/torch/nn/intrinsic/quantized/modules/conv_relu/___torch_mangle_705.py", line 91, in forward1
        argument_1: Tensor) -> Tensor:
        _packed_params = self._packed_params
        input = ops.quantized.conv2d_relu(argument_1, _packed_params, 0.037418920546770096, 0)
                ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
E/AndroidRuntime:     return input
      def forward2(self: __torch__.torch.nn.intrinsic.quantized.modules.conv_relu.___torch_mangle_705.ConvReLU2d,
    
    Traceback of TorchScript, original code (most recent call last):
      File "C:\PycharmProjects\pyn2\create_d2go.py", line 70, in forward
                scale = 320.0 / min(x.shape[-2], x.shape[-1])
                x = torch.nn.functional.interpolate(x, scale_factor=scale, mode="bilinear", align_corners=True, recompute_scale_factor=True)
                out = self.model(x[0])
                      ~~~~~~~~~~ <--- HERE
                res : Dict[str, torch.Tensor] = {}
                res["boxes"] = out[0] / scale
    C:\PycharmProjects\pyn2\venv\lib\site-packages\torch\nn\intrinsic\quantized\modules\conv_relu.py(85): forward
    C:\PycharmProjects\pyn2\venv\lib\site-packages\torch\nn\modules\module.py(1098): _slow_forward
    C:\PycharmProjects\pyn2\venv\lib\site-packages\torch\nn\modules\module.py(1110): _call_impl
    C:\PycharmProjects\pyn2\venv\lib\site-packages\mobile_cv\arch\fbnet_v2\basic_blocks.py(457): forward
    C:\PycharmProjects\pyn2\venv\lib\site-packages\torch\nn\modules\module.py(1098): _slow_forward
    C:\PycharmProjects\pyn2\venv\lib\site-packages\torch\nn\modules\module.py(1110): _call_impl
    C:\PycharmProjects\pyn2\venv\lib\site-packages\mobile_cv\arch\fbnet_v2\irf_block.py(203): forward
    C:\PycharmProjects\pyn2\venv\lib\site-packages\torch\nn\modules\module.py(1098): _slow_forward
    C:\PycharmProjects\pyn2\venv\lib\site-packages\torch\nn\modules\module.py(1110): _call_impl
    C:\PycharmProjects\pyn2\venv\lib\site-packages\torch\nn\modules\container.py(141): forward
    C:\PycharmProjects\pyn2\venv\lib\site-packages\torch\nn\modules\module.py(1098): _slow_forward
    C:\PycharmProjects\pyn2\venv\lib\site-packages\torch\nn\modules\module.py(1110): _call_impl
    C:\PycharmProjects\pyn2\venv\lib\site-packages\torch\nn\modules\container.py(141): forward
    C:\PycharmProjects\pyn2\venv\lib\site-packages\torch\nn\modules\module.py(1098): _slow_forward
    C:\PycharmProjects\pyn2\venv\lib\site-packages\torch\nn\modules\module.py(1110): _call_impl
    C:\PycharmProjects\pyn2\venv\lib\site-packages\d2go\modeling\backbone\fbnet_v2.py(359): <listcomp>
    C:\PycharmProjects\pyn2\venv\lib\site-packages\d2go\modeling\backbone\fbnet_v2.py(359): forward
    C:\PycharmProjects\pyn2\venv\lib\site-packages\mobile_cv\arch\utils\quantize_utils.py(345): wrapped_method
    C:\PycharmProjects\pyn2\venv\lib\site-packages\torch\nn\modules\module.py(1098): _slow_forward
    C:\PycharmProjects\pyn2\venv\lib\site-packages\torch\nn\modules\module.py(1110): _call_impl
    C:\PycharmProjects\pyn2\venv\lib\site-packages\detectron2\modeling\proposal_generator\rpn.py(454): forward
    C:\PycharmProjects\pyn2\venv\lib\site-packages\torch\nn\modules\module.py(1098): _slow_forward
    C:\PycharmProjects\pyn2\venv\lib\site-packages\torch\nn\modules\module.py(1110): _call_impl
    C:\PycharmProjects\pyn2\venv\lib\site-packages\detectron2\modeling\meta_arch\rcnn.py(204): inference
    C:\PycharmProjects\pyn2\venv\lib\site-packages\d2go\modeling\meta_arch\rcnn.py(404): forward
    C:\PycharmProjects\pyn2\venv\lib\site-packages\torch\nn\modules\module.py(1098): _slow_forward
    C:\PycharmProjects\pyn2\venv\lib\site-packages\torch\nn\modules\module.py(1110): _call_impl
    C:\PycharmProjects\pyn2\venv\lib\site-packages\detectron2\export\flatten.py(259): <lambda>
    C:\PycharmProjects\pyn2\venv\lib\site-packages\detectron2\export\flatten.py(294): forward
    C:\PycharmProjects\pyn2\venv\lib\site-packages\torch\nn\modules\module.py(1098): _slow_forward
    C:\PycharmProjects\pyn2\venv\lib\site-packages\torch\nn\modules\module.py(1110): _call_impl
    C:\PycharmProjects\pyn2\venv\lib\site-packages\torch\jit\_trace.py(958): trace_module
    C:\PycharmProjects\pyn2\venv\lib\site-packages\torch\jit\_trace.py(741): trace
    C:\PycharmProjects\pyn2\venv\lib\site-packages\d2go\export\torchscript.py(79): export_optimize_and_save_torchscript
    C:\PycharmProjects\pyn2\venv\lib\site-packages\d2go\export\torchscript.py(364): export
    C:\PycharmProjects\pyn2\venv\lib\site-packages\d2go\export\torchscript.py(348): new_f
    C:\PycharmProjects\pyn2\venv\lib\site-packages\d2go\export\torchscript.py(393): export
    C:\PycharmProjects\pyn2\venv\lib\site-packages\d2go\export\torchscript.py(232): new_f
    C:\PycharmProjects\pyn2\venv\lib\site-packages\d2go\export\torchscript.py(348): new_f
    C:\PycharmProjects\pyn2\venv\lib\site-packages\d2go\export\api.py(196): _export_single_model
    C:\PycharmProjects\pyn2\venv\lib\site-packages\d2go\export\api.py(262): default_export_predictor
    C:\PycharmProjects\pyn2\venv\lib\site-packages\d2go\export\api.py(174): export_predictor
    C:\PycharmProjects\pyn2\venv\lib\site-packages\d2go\export\api.py(151): convert_and_export_predictor
    C:\PycharmProjects\pyn2\create_d2go.py(80): test_export_torchvision_format
    C:\PycharmProjects\pyn2\create_d2go.py(96): <module>
    RuntimeError: Output channel size of weight and bias must match.
    
        at org.pytorch.NativePeer.forward(Native Method)
        at org.pytorch.Module.forward(Module.java:52)
        at org.pytorch.demo.objectdetection.MainActivity.run(MainActivity.java:241)
        at java.lang.Thread.run(Thread.java:923)

'''
