### ISSUE TITLE
No module named 'mobile_cv.arch.builder'

### ISSUE THREAD

**Issue by RivkinMikhail** [facebookresearch/d2go#178]
Hello everyone and thank you for this great repo!

I'm trying to run the demo.py code and get this error message. 

`Traceback (most recent call last):
  File "demo/demo.py", line 11, in <module>
    from d2go.model_zoo import model_zoo
  File "/media/cockatiel/ea7f0e24-9c25-4b22-8251-d3b1ca8a835f/kiosks/d2go/d2go/__init__.py", line 7, in <module>
    from d2go import initializer, optimizer  # NOQA
  File "/media/cockatiel/ea7f0e24-9c25-4b22-8251-d3b1ca8a835f/kiosks/d2go/d2go/initializer.py", line 67, in <module>
    initialize_all()
  File "/media/cockatiel/ea7f0e24-9c25-4b22-8251-d3b1ca8a835f/kiosks/d2go/d2go/initializer.py", line 62, in initialize_all
    _register()
  File "/media/cockatiel/ea7f0e24-9c25-4b22-8251-d3b1ca8a835f/kiosks/d2go/d2go/initializer.py", line 17, in timed_f
    ret = f(*args, **kwargs)
  File "/media/cockatiel/ea7f0e24-9c25-4b22-8251-d3b1ca8a835f/kiosks/d2go/d2go/initializer.py", line 48, in _register
    from d2go.modeling.backbone import (  # NOQA
  File "/media/cockatiel/ea7f0e24-9c25-4b22-8251-d3b1ca8a835f/kiosks/d2go/d2go/modeling/__init__.py", line 6, in <module>
    from . import backbone  # noqa
  File "/media/cockatiel/ea7f0e24-9c25-4b22-8251-d3b1ca8a835f/kiosks/d2go/d2go/modeling/backbone/__init__.py", line 4, in <module>
    from . import fbnet_v2
  File "/media/cockatiel/ea7f0e24-9c25-4b22-8251-d3b1ca8a835f/kiosks/d2go/d2go/modeling/backbone/fbnet_v2.py", line 23, in <module>
    from mobile_cv.arch.fbnet_v2 import fbnet_builder as mbuilder
  File "/media/cockatiel/ea7f0e24-9c25-4b22-8251-d3b1ca8a835f/venvs/d2go/lib/python3.8/site-packages/mobile_cv/arch/fbnet_v2/fbnet_builder.py", line 8, in <module>
    from mobile_cv.arch.builder.meta_builder import *  # noqa
ModuleNotFoundError: No module named 'mobile_cv.arch.builder'
`

Following the installation guide, I didn't face any errors while installing, except one connected to module 'importlib.util' (as far as I understand it is pre-installed in Python 3.8 so I removed it from the setup.py)

I have only CPU computer and this is my dependency list if it is necessary

`absl-py                 1.0.0                 
aiohttp                 3.8.1                 
aiosignal               1.2.0                 
antlr4-python3-runtime  4.8                   
appdirs                 1.4.4                 
async-timeout           4.0.2                 
attrs                   21.4.0                
black                   21.4b2                
cachetools              5.0.0                 
certifi                 2021.10.8             
charset-normalizer      2.0.12                
click                   8.0.3                 
cloudpickle             2.0.0                 
cycler                  0.11.0                
d2go                    0.0.1b20220216        
detectron2              0.6                   
fonttools               4.29.1                
frozenlist              1.3.0                 
fsspec                  2022.1.0              
future                  0.18.2                
fvcore                  0.1.5.post20220212    
google-auth             2.6.0                 
google-auth-oauthlib    0.4.6                 
grpcio                  1.43.0                
hydra-core              1.1.1                 
idna                    3.3                   
importlib-metadata      4.11.1                
importlib-resources     5.4.0                 
iopath                  0.1.9                 
kiwisolver              1.3.2                 
Markdown                3.3.6                 
matplotlib              3.5.1                 
mobile-cv               0.1                   
mock                    4.0.3                 
multidict               6.0.2                 
mypy-extensions         0.4.3                 
numpy                   1.22.2                
oauthlib                3.2.0                 
omegaconf               2.1.1                 
opencv-python           4.5.5.62              
packaging               21.3                  
parameterized           0.8.1                 
pathspec                0.9.0                 
Pillow                  9.0.1                 
pip                     20.0.2                
pkg-resources           0.0.0                 
portalocker             2.3.2                 
protobuf                3.19.4                
pyasn1                  0.4.8                 
pyasn1-modules          0.2.8                 
pycocotools             2.0.4                 
pyDeprecate             0.3.1                 
pydot                   1.4.2                 
pyparsing               3.0.7                 
python-dateutil         2.8.2                 
pytorch-lightning       1.5.10                
PyYAML                  6.0                   
regex                   2022.1.18             
requests                2.27.1                
requests-oauthlib       1.3.1                 
rsa                     4.8                   
scipy                   1.8.0                 
setuptools              59.5.0                
six                     1.16.0                
tabulate                0.8.9                 
tensorboard             2.8.0                 
tensorboard-data-server 0.6.1                 
tensorboard-plugin-wit  1.8.1                 
termcolor               1.1.0                 
toml                    0.10.2                
torch                   1.12.0.dev20220216+cpu
torchaudio              0.11.0.dev20220216+cpu
torchmetrics            0.7.2                 
torchvision             0.13.0.dev20220216+cpu
tqdm                    4.62.3                
typing-extensions       4.1.1                 
urllib3                 1.26.8                
Werkzeug                2.0.3                 
wheel                   0.37.1                
yacs                    0.1.8                 
yarl                    1.7.2                 
zipp                    3.7.0  `

**Comment by zhanghang1989** [comment]
Could you reinstall the mobile-vision library? https://github.com/facebookresearch/mobile-vision

**Comment by wat3rBro** [comment]
Maybe https://github.com/facebookresearch/mobile-vision/pull/62/files has fixed this?
