### ISSUE TITLE
AttributeError: module 'detr' has no attribute 'datasets'

### ISSUE THREAD

**Issue by LegendBC** [facebookresearch/d2go#18]
Hi, thanks for your great work!
An error occured when I follow the instruction of detr subproject.
I ran the command as  instructed in [detr readme](https://github.com/facebookresearch/d2go/blob/master/projects_oss/detr/README.md) 
```
:~/d2go$ python tools/train_net.py --runner detr.runner.DETRRunner  --config projects_oss/detr/configs/deformable_detr_fbnetv3a_bs16.yaml
```

Then an error occured:
```
** fvcore version of PathManager will be deprecated soon. **
** Please migrate to the version in iopath repo. **
https://github.com/facebookresearch/iopath

Namespace(config_file='projects_oss/detr/configs/deformable_detr_fbnetv3a_bs16.yaml', dist_backend='NCCL', dist_url='file:///tmp/d2go_dist_file_1615526898.7341282', eval_only=False, machine_rank=0, num_machines=1, num_processes=1, opts=[], output_dir=None, resume=False, runner='detr.runner.DETRRunner')
Traceback (most recent call last):
  File "tools/train_net.py", line 104, in <module>
    cli()
  File "tools/train_net.py", line 101, in cli
    run_with_cmdline_args(parser.parse_args())
  File "tools/train_net.py", line 80, in run_with_cmdline_args
    cfg, output_dir, runner = prepare_for_launch(args)
  File "/home/lbc/anaconda3/envs/d2go/lib/python3.6/site-packages/d2go/setup.py", line 165, in prepare_for_launch
    runner = create_runner(args.runner)
  File "/home/lbc/anaconda3/envs/d2go/lib/python3.6/site-packages/d2go/runner/__init__.py", line 20, in create_runner
    runner_class = get_class(class_full_name)
  File "/home/lbc/anaconda3/envs/d2go/lib/python3.6/site-packages/d2go/runner/__init__.py", line 13, in get_class
    runner_module = importlib.import_module(runner_module_name)
  File "/home/lbc/anaconda3/envs/d2go/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lbc/anaconda3/envs/d2go/lib/python3.6/site-packages/detr-0.0.0-py3.6-linux-x86_64.egg/detr/__init__.py", line 3, in <module>
    from . import models, util, datasets
  File "/home/lbc/anaconda3/envs/d2go/lib/python3.6/site-packages/detr-0.0.0-py3.6-linux-x86_64.egg/detr/datasets/__init__.py", line 7, in <module>
    from .coco import build as build_coco
  File "/home/lbc/anaconda3/envs/d2go/lib/python3.6/site-packages/detr-0.0.0-py3.6-linux-x86_64.egg/detr/datasets/coco.py", line 16, in <module>
    import detr.datasets.transforms as T
AttributeError: module 'detr' has no attribute 'datasets'

```

**Comment by zhanghang1989** [comment]
The file is located at:
https://github.com/facebookresearch/d2go/blob/master/projects_oss/detr/detr/datasets/transforms.py

Could you check your local path? Do you have a file named detr in your current folder?

**Comment by REXIMMORTAL** [comment]
> The file is located at:
> https://github.com/facebookresearch/d2go/blob/master/projects_oss/detr/detr/datasets/transforms.py
> 
> Could you check your local path? Do you have a file named detr in your current folder?

Thanks for your quick reply! Yes,  I do have detr in my current folder. Everything is algned with remote repo.
```
:~/d2go/projects_oss/detr/detr/datasets$ ls
coco_eval.py  coco_panoptic.py  coco.py  __init__.py  panoptic_eval.py  __pycache__  transforms.py
```

**Comment by REXIMMORTAL** [comment]
My current folder where command run is organized as followed:
```
~/d2go$ ls
build  configs  d2go  d2go.egg-info  datasets  demo  dist  LICENSE  model_0479999.pth  MODEL_ZOO.md  output  projects_oss  README.md  setup.py  tests  tools
```

**Comment by zhanghang1989** [comment]
It seems just a python importing issue. Please check whether you have a conflicted `detr.py` file for `detr/` folder in your current directory or `PYTHONPATH`. 

Try running the command in a different directory:
```bash
cd projects_oss/detr/configs/
d2go.train_net  --runner detr.runner.DETRRunner  --config  deformable_detr_fbnetv3a_bs16.yaml
```

**Comment by REXIMMORTAL** [comment]
Thanks for your reply!
My`<d2go>/projects_oss/detr`  dir organized as follow:
```
:~/d2go/projects_oss/detr$ ls
build  configs  detr  detr.egg-info  dist  LICENSE  model_final.pth  README.md  setup.py  test_all.py  test_op.py  train_net.py
```
I ran the `d2go.train_net  --runner detr.runner.DETRRunner  --config  deformable_detr_fbnetv3a_bs16.yaml` in `<d2go>/projects_oss/detr/configs` path. The same error reported.
```
~/d2go/projects_oss/detr/configs$ d2go.train_net  --runner detr.runner.DETRRunner  --config  deformable_detr_fbnetv3a_bs16.yaml
** fvcore version of PathManager will be deprecated soon. **
** Please migrate to the version in iopath repo. **
https://github.com/facebookresearch/iopath

Namespace(config_file='deformable_detr_fbnetv3a_bs16.yaml', dist_backend='NCCL', dist_url='file:///tmp/d2go_dist_file_1615528696.1488786', eval_only=False, machine_rank=0, num_machines=1, num_processes=1, opts=[], output_dir=None, resume=False, runner='detr.runner.DETRRunner')
Traceback (most recent call last):
  File "/home/lbc/anaconda3/envs/d2go/bin/d2go.train_net", line 8, in <module>
    sys.exit(cli())
  File "/home/lbc/anaconda3/envs/d2go/lib/python3.6/site-packages/d2go/tools/train_net.py", line 101, in cli
    run_with_cmdline_args(parser.parse_args())
  File "/home/lbc/anaconda3/envs/d2go/lib/python3.6/site-packages/d2go/tools/train_net.py", line 80, in run_with_cmdline_args
    cfg, output_dir, runner = prepare_for_launch(args)
  File "/home/lbc/anaconda3/envs/d2go/lib/python3.6/site-packages/d2go/setup.py", line 165, in prepare_for_launch
    runner = create_runner(args.runner)
  File "/home/lbc/anaconda3/envs/d2go/lib/python3.6/site-packages/d2go/runner/__init__.py", line 20, in create_runner
    runner_class = get_class(class_full_name)
  File "/home/lbc/anaconda3/envs/d2go/lib/python3.6/site-packages/d2go/runner/__init__.py", line 13, in get_class
    runner_module = importlib.import_module(runner_module_name)
  File "/home/lbc/anaconda3/envs/d2go/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lbc/anaconda3/envs/d2go/lib/python3.6/site-packages/detr-0.0.0-py3.6-linux-x86_64.egg/detr/__init__.py", line 3, in <module>
    from . import models, util, datasets
  File "/home/lbc/anaconda3/envs/d2go/lib/python3.6/site-packages/detr-0.0.0-py3.6-linux-x86_64.egg/detr/datasets/__init__.py", line 7, in <module>
    from .coco import build as build_coco
  File "/home/lbc/anaconda3/envs/d2go/lib/python3.6/site-packages/detr-0.0.0-py3.6-linux-x86_64.egg/detr/datasets/coco.py", line 16, in <module>
    import detr.datasets.transforms as T
AttributeError: module 'detr' has no attribute 'datasets'

```

**Comment by zhanghang1989** [comment]
sorry for the late reply. did you follow the instruction to install the package? https://github.com/facebookresearch/d2go/tree/main/projects_oss/detr#usage
