### ISSUE TITLE
Unable to train: AttributeError: BASE_LR_END

### ISSUE THREAD

**Issue by akiross** [facebookresearch/d2go#217]
## Instructions To Reproduce the 🐛 Bug:
1. Full runnable code or full changes you made:

There's a small patch to make this work with torch 1.10
```
git rev-parse HEAD; git diff
c055a84f1c2dc66badb07101a4515c82cd47c332
diff --git a/d2go/modeling/meta_arch/rcnn.py b/d2go/modeling/meta_arch/rcnn.py
index 0a7c86f..5d48955 100644
--- a/d2go/modeling/meta_arch/rcnn.py
+++ b/d2go/modeling/meta_arch/rcnn.py
@@ -20,8 +20,8 @@ from mobile_cv.arch.utils.quantize_utils import (
     QuantWrapper,
 )
 from mobile_cv.predictor.api import FuncInfo
-from torch.ao.quantization import convert
-from torch.ao.quantization.quantize_fx import prepare_fx, prepare_qat_fx, convert_fx
+from torch.quantization import convert
+from torch.quantization.quantize_fx import prepare_fx, prepare_qat_fx, convert_fx

 logger = logging.getLogger(__name__)

diff --git a/d2go/runner/callbacks/quantization.py b/d2go/runner/callbacks/quantization.py
index e6986dc..af43cdd 100644
--- a/d2go/runner/callbacks/quantization.py
+++ b/d2go/runner/callbacks/quantization.py
@@ -13,15 +13,15 @@ from mobile_cv.arch.quantization.observer import update_stat as observer_update_
 from pytorch_lightning import LightningModule, Trainer
 from pytorch_lightning.callbacks import Callback
 from pytorch_lightning.utilities import rank_zero_info
-from torch.ao.quantization import (  # @manual
+from torch.quantization import (  # @manual
     QConfig,
     QConfigDynamic,
     QuantType,
     get_default_qat_qconfig,
     get_default_qconfig,
 )
-from torch.ao.quantization.quantize_fx import convert_fx, prepare_fx, prepare_qat_fx
-from torch.ao.quantization.utils import get_quant_type
+from torch.quantization.quantize_fx import convert_fx, prepare_fx, prepare_qat_fx
+from torch.quantization.utils import get_quant_type


 QConfigDicts = Dict[str, Dict[str, Union[QConfig, QConfigDynamic]]]
```

3. What exact command you run:

I ran the following
```
python3 tools/train_net.py --config-file ./configs/keypoint_rcnn_fbnetv3a_dsmask_C4.yaml
```

instead of `d2go.train_net` as the latter is giving an error (`TypeError: cli() missing 1 required positional argument: 'args'`).

5. __Full logs__ or other relevant observations:
```
Loaded config file ./configs/keypoint_rcnn_fbnetv3a_dsmask_C4.yaml:
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  KEYPOINT_ON: True
  MASK_ON: False
  # WEIGHTS: manifold://xiaoliangdai_model/tree/xiaoliangdai/20210126/faster_rcnn.ULfbyCBZtx/e2e_train/model_0179999.pth
  FBNET_V2:
    ARCH: "FBNetV3_A_dsmask"
    NORM: "naiveSyncBN"
    WIDTH_DIVISOR: 8
    SCALE_FACTOR: 0.75
  BACKBONE:
    NAME: FBNetV2C4Backbone
  ANCHOR_GENERATOR:
    # SIZES: [[32, 64, 128, 256, 512]]  # NOTE: for smaller resolution (320 < 512)
    SIZES: [[32, 64, 96, 128, 160]]  # NOTE: for smaller resolution (320 < 512)
  RPN:
    HEAD_NAME: FBNetV2RpnHead
    IN_FEATURES: ["trunk3"]
    # Default values are 12000/2000 for train and 6000/1000 for test. In FBNet
    # we use smaller numbers.  TODO: reduce proposals for test in .yaml directly.
    POST_NMS_TOPK_TEST: 30
    POST_NMS_TOPK_TRAIN: 1000
    PRE_NMS_TOPK_TEST: 6000
    PRE_NMS_TOPK_TRAIN: 4000
  ROI_HEADS:
    NUM_CLASSES: 1
    IN_FEATURES: ["trunk3"]
    NAME: StandardROIHeads
  ROI_BOX_HEAD:
    SMOOTH_L1_BETA: 0.5  # 1.0? Keypoint AP degrades (though box AP improves) when using plain L1 loss
    NAME: FBNetV2RoIBoxHead
    POOLER_RESOLUTION: 6
    NORM: "naiveSyncBN"
  ROI_MASK_HEAD:
    NAME: "FBNetV2RoIMaskHead"
    NUM_CONV: 0
    POOLER_RESOLUTION: 6
  ROI_KEYPOINT_HEAD:
    NAME: FBNetV2RoIKeypointHeadKPRCNNIRFPredictorNoUpscale
    POOLER_RESOLUTION: 6
    POOLER_SAMPLING_RATIO: 0
    POOLER_TYPE: ROIAlignV2
    # NUM_KEYPOINTS: 100
  PIXEL_MEAN: [103.53, 116.28, 123.675]
  PIXEL_STD: [57.375, 57.12, 58.395]
MODEL_EMA:
  ENABLED: True
  DECAY: 0.9998
DATASETS:
  TRAIN: ("keypoints_coco_2017_train",)
  TEST: ("keypoints_coco_2017_val",)
  # TRAIN: ("02-11-2020_999tasks", "17-11-2020_545tasks", "06-11-2020_623tasks", "30-10-2020_602tasks")
  # TEST: ("11-11-2020_387tasks",)
#DATALOADER:
  #NUM_WORKERS: 0
SOLVER:
  IMS_PER_BATCH: 32
  BASE_LR: 0.16
  MAX_ITER: 450000
  LR_SCHEDULER_NAME: WarmupCosineLR
TEST:
  EVAL_PERIOD: 5000
  # KEYPOINT_OKS_SIGMAS: [0.025, 0.025, 0.025, 0.025, 0.025, 0.025, 0.025, 0.025, 0.025, 0.025, 0.025, 0.025, 0.025, 0.025, 0.025, 0.025, 0.025, 0.025, 0.025, 0.025, 0.025]
INPUT:
  MAX_SIZE_TEST: 448
  MAX_SIZE_TRAIN: 448
  MIN_SIZE_TEST: 224
  MIN_SIZE_TRAIN: (224,)
VERSION: 2
EXPORT_CAFFE2:
  USE_HEATMAP_MAX_KEYPOINT: True
#MODEL_EMA:
#  DECAY: 0.9998
#  DEVICE:
#  ENABLED: True
#  USE_EMA_WEIGHTS_FOR_EVAL_ONLY: True

[04/21 21:20:28 d2go.setup]: Full config saved to ./output/config.yaml
[04/21 21:20:28 d2go.setup]: Initializing runner ...
[04/21 21:20:28 d2go.setup]: Using 1 processes per machine. Rank of current process: 0
[04/21 21:20:29 d2go.setup]: Environment info:
----------------------  ----------------------------------------------------------
sys.platform            linux
Python                  3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
numpy                   1.21.2
detectron2              0.6 @/opt/conda/lib/python3.7/site-packages/detectron2
Compiler                GCC 7.3
CUDA compiler           CUDA 11.1
detectron2 arch flags   3.7, 5.0, 5.2, 6.0, 6.1, 7.0, 7.5, 8.0, 8.6
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.10.0 @/opt/conda/lib/python3.7/site-packages/torch
PyTorch debug build     False
GPU available           Yes
GPU 0                   NVIDIA GeForce GTX 1650 (arch=7.5)
Driver version          510.60.02
CUDA_HOME               /usr/local/cuda
Pillow                  8.4.0
torchvision             0.11.0 @/opt/conda/lib/python3.7/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5, 8.0, 8.6
fvcore                  0.1.5.post20220414
iopath                  0.1.9
cv2                     4.5.5
----------------------  ----------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.3-Product Build 20210617 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

[04/21 21:20:29 d2go.setup]: Running with full config:
ABNORMAL_CHECKER:
  ENABLED: False
CUDNN_BENCHMARK: False
D2GO_DATA:
  AUG_OPS:
    TEST: ['ResizeShortestEdgeOp']
    TRAIN: ['ResizeShortestEdgeOp', 'RandomFlipOp']
  DATASETS:
    COCO_INJECTION:
      IM_DIRS: []
      JSON_FILES: []
      KEYPOINT_METADATA: []
      NAMES: []
      REGISTER_FUNCTION: _register_extended_coco
    DISK_CACHE:
      ENABLED: False
    DYNAMIC_DATASETS: []
    TEST_CATEGORIES: ()
    TRAIN_CATEGORIES: ()
  MAPPER:
    BACKFILL_SIZE: False
    CATCH_EXCEPTION: True
    NAME: D2GoDatasetMapper
    RETRY: 3
  TEST:
    MAX_IMAGES: 0
    SUBSET_SAMPLING: frontmost
DATALOADER:
  ASPECT_RATIO_GROUPING: True
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4
  RANDOM_SUBSET_RATIO: 1.0
  REPEAT_THRESHOLD: 0.0
  SAMPLER_TRAIN: TrainingSampler
DATASETS:
  PRECOMPUTED_PROPOSAL_TOPK_TEST: 1000
  PRECOMPUTED_PROPOSAL_TOPK_TRAIN: 2000
  PROPOSAL_FILES_TEST: ()
  PROPOSAL_FILES_TRAIN: ()
  TEST: ('keypoints_coco_2017_val',)
  TRAIN: ('keypoints_coco_2017_train',)
  TRAIN_REPEAT_FACTOR: []
EXPORT_CAFFE2:
  USE_HEATMAP_MAX_KEYPOINT: True
GLOBAL:
  HACK: 1.0
INPUT:
  CROP:
    ENABLED: False
    SIZE: [0.9, 0.9]
    TYPE: relative_range
  FORMAT: BGR
  MASK_FORMAT: polygon
  MAX_SIZE_TEST: 448
  MAX_SIZE_TRAIN: 448
  MIN_SIZE_TEST: 224
  MIN_SIZE_TRAIN: (224,)
  MIN_SIZE_TRAIN_SAMPLING: choice
  RANDOM_FLIP: horizontal
  RECOMPUTE_BOXES: False
MODEL:
  ANCHOR_GENERATOR:
    ANGLES: [[-90, 0, 90]]
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]
    NAME: DefaultAnchorGenerator
    OFFSET: 0.0
    SIZES: [[32, 64, 96, 128, 160]]
  BACKBONE:
    FREEZE_AT: 2
    NAME: FBNetV2C4Backbone
  DDP_FIND_UNUSED_PARAMETERS: False
  DDP_FP16_GRAD_COMPRESS: False
  DEVICE: cuda
  FBNET_V2:
    ARCH: FBNetV3_A_dsmask
    ARCH_DEF: []
    NORM: naiveSyncBN
    NORM_ARGS: []
    SCALE_FACTOR: 0.75
    STEM_IN_CHANNELS: 3
    WIDTH_DIVISOR: 8
  FCOS:
    FOCAL_LOSS_ALPHA: 0.25
    FOCAL_LOSS_GAMMA: 2.0
    HEAD_NORM: GN
    IN_FEATURES: ['p3', 'p4', 'p5', 'p6', 'p7']
    NMS_THRESH_TEST: 0.6
    NUM_CLASSES: 80
    NUM_CONVS: 4
    SCORE_THRESH_TEST: 0.04
    TOPK_CANDIDATES_TEST: 1000
  FPN:
    FUSE_TYPE: sum
    IN_FEATURES: []
    NORM: 
    OUT_CHANNELS: 256
  FROZEN_LAYER_REG_EXP: []
  KEYPOINT_ON: True
  KMEANS_ANCHORS:
    DATASETS: ()
    KMEANS_ANCHORS_ON: False
    NUM_CLUSTERS: 0
    NUM_TRAINING_IMG: 0
    RNG_SEED: 3
  LOAD_PROPOSALS: False
  MASK_ON: False
  META_ARCHITECTURE: GeneralizedRCNN
  PANOPTIC_FPN:
    COMBINE:
      ENABLED: True
      INSTANCES_CONFIDENCE_THRESH: 0.5
      OVERLAP_THRESH: 0.5
      STUFF_AREA_LIMIT: 4096
    INSTANCE_LOSS_WEIGHT: 1.0
  PIXEL_MEAN: [103.53, 116.28, 123.675]
  PIXEL_STD: [57.375, 57.12, 58.395]
  PROPOSAL_GENERATOR:
    MIN_SIZE: 0
    NAME: RPN
  RESNETS:
    DEFORM_MODULATED: False
    DEFORM_NUM_GROUPS: 1
    DEFORM_ON_PER_STAGE: [False, False, False, False]
    DEPTH: 50
    NORM: FrozenBN
    NUM_GROUPS: 1
    OUT_FEATURES: ['res4']
    RES2_OUT_CHANNELS: 256
    RES5_DILATION: 1
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: True
    WIDTH_PER_GROUP: 64
  RETINANET:
    BBOX_REG_LOSS_TYPE: smooth_l1
    BBOX_REG_WEIGHTS: (1.0, 1.0, 1.0, 1.0)
    FOCAL_LOSS_ALPHA: 0.25
    FOCAL_LOSS_GAMMA: 2.0
    IN_FEATURES: ['p3', 'p4', 'p5', 'p6', 'p7']
    IOU_LABELS: [0, -1, 1]
    IOU_THRESHOLDS: [0.4, 0.5]
    NMS_THRESH_TEST: 0.5
    NORM: 
    NUM_CLASSES: 80
    NUM_CONVS: 4
    PRIOR_PROB: 0.01
    SCORE_THRESH_TEST: 0.05
    SMOOTH_L1_LOSS_BETA: 0.1
    TOPK_CANDIDATES_TEST: 1000
  ROI_BOX_CASCADE_HEAD:
    BBOX_REG_WEIGHTS: ((10.0, 10.0, 5.0, 5.0), (20.0, 20.0, 10.0, 10.0), (30.0, 30.0, 15.0, 15.0))
    IOUS: (0.5, 0.6, 0.7)
  ROI_BOX_HEAD:
    BBOX_REG_LOSS_TYPE: smooth_l1
    BBOX_REG_LOSS_WEIGHT: 1.0
    BBOX_REG_WEIGHTS: (10.0, 10.0, 5.0, 5.0)
    CLS_AGNOSTIC_BBOX_REG: False
    CONV_DIM: 256
    FC_DIM: 1024
    NAME: FBNetV2RoIBoxHead
    NORM: naiveSyncBN
    NUM_CONV: 0
    NUM_FC: 0
    POOLER_RESOLUTION: 6
    POOLER_SAMPLING_RATIO: 0
    POOLER_TYPE: ROIAlignV2
    SMOOTH_L1_BETA: 0.5
    TRAIN_ON_PRED_BOXES: False
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 512
    IN_FEATURES: ['trunk3']
    IOU_LABELS: [0, 1]
    IOU_THRESHOLDS: [0.5]
    NAME: StandardROIHeads
    NMS_THRESH_TEST: 0.5
    NUM_CLASSES: 1
    POSITIVE_FRACTION: 0.25
    PROPOSAL_APPEND_GT: True
    SCORE_THRESH_TEST: 0.05
  ROI_KEYPOINT_HEAD:
    CONV_DIMS: (512, 512, 512, 512, 512, 512, 512, 512)
    LOSS_WEIGHT: 1.0
    MIN_KEYPOINTS_PER_IMAGE: 1
    NAME: FBNetV2RoIKeypointHeadKPRCNNIRFPredictorNoUpscale
    NORMALIZE_LOSS_BY_VISIBLE_KEYPOINTS: True
    NUM_KEYPOINTS: 17
    POOLER_RESOLUTION: 6
    POOLER_SAMPLING_RATIO: 0
    POOLER_TYPE: ROIAlignV2
  ROI_MASK_HEAD:
    CLS_AGNOSTIC_MASK: False
    CONV_DIM: 256
    NAME: FBNetV2RoIMaskHead
    NORM: 
    NUM_CONV: 0
    POOLER_RESOLUTION: 6
    POOLER_SAMPLING_RATIO: 0
    POOLER_TYPE: ROIAlignV2
  RPN:
    BATCH_SIZE_PER_IMAGE: 256
    BBOX_REG_LOSS_TYPE: smooth_l1
    BBOX_REG_LOSS_WEIGHT: 1.0
    BBOX_REG_WEIGHTS: (1.0, 1.0, 1.0, 1.0)
    BOUNDARY_THRESH: -1
    CONV_DIMS: [-1]
    HEAD_NAME: FBNetV2RpnHead
    IN_FEATURES: ['trunk3']
    IOU_LABELS: [0, -1, 1]
    IOU_THRESHOLDS: [0.3, 0.7]
    LOSS_WEIGHT: 1.0
    NMS_THRESH: 0.7
    POSITIVE_FRACTION: 0.5
    POST_NMS_TOPK_TEST: 30
    POST_NMS_TOPK_TRAIN: 1000
    PRE_NMS_TOPK_TEST: 6000
    PRE_NMS_TOPK_TRAIN: 4000
    SMOOTH_L1_BETA: 0.0
  SEM_SEG_HEAD:
    COMMON_STRIDE: 4
    CONVS_DIM: 128
    IGNORE_VALUE: 255
    IN_FEATURES: ['p2', 'p3', 'p4', 'p5']
    LOSS_WEIGHT: 1.0
    NAME: SemSegFPNHead
    NORM: GN
    NUM_CLASSES: 54
  SUBCLASS:
    NUM_LAYERS: 1
    NUM_SUBCLASSES: 0
    SUBCLASS_ID_FETCHER: SubclassFetcher
    SUBCLASS_MAPPING: []
    SUBCLASS_ON: False
  VT_FPN:
    HEADS: 16
    IN_FEATURES: ['res2', 'res3', 'res4', 'res5']
    LAYERS: 3
    MIN_GROUP_PLANES: 64
    NORM: BN
    OUT_CHANNELS: 256
    POS_HWS: []
    POS_N_DOWNSAMPLE: []
    TOKEN_C: 1024
    TOKEN_LS: [16, 16, 8, 8]
  WEIGHTS: 
MODEL_EMA:
  DECAY: 0.9998
  DEVICE: 
  ENABLED: True
  USE_EMA_WEIGHTS_FOR_EVAL_ONLY: False
OUTPUT_DIR: ./output
PROFILERS: ['default_flop_counter']
QUANTIZATION:
  BACKEND: fbgemm
  CUSTOM_QSCHEME: 
  EAGER_MODE: True
  MODULES: []
  NAME: 
  PTQ:
    CALIBRATION_FORCE_ON_GPU: False
    CALIBRATION_NUM_IMAGES: 1
  QAT:
    BATCH_SIZE_FACTOR: 1.0
    DISABLE_OBSERVER_ITER: 38000
    ENABLED: False
    ENABLE_LEARNABLE_OBSERVER_ITER: 36000
    ENABLE_OBSERVER_ITER: 35000
    FAKE_QUANT_METHOD: default
    FREEZE_BN_ITER: 37000
    START_ITER: 35000
    UPDATE_OBSERVER_STATS_PERIOD: 1
    UPDATE_OBSERVER_STATS_PERIODICALLY: False
RCNN_EXPORT:
  INCLUDE_POSTPROCESS: False
RCNN_PREPARE_FOR_EXPORT: default_rcnn_prepare_for_export
RCNN_PREPARE_FOR_QUANT: default_rcnn_prepare_for_quant
RCNN_PREPARE_FOR_QUANT_CONVERT: default_rcnn_prepare_for_quant_convert
SEED: -1
SOLVER:
  AMP:
    ENABLED: False
  AUTO_SCALING_METHODS: ['default_scale_d2_configs', 'default_scale_quantization_configs']
  BASE_LR: 0.16
  BIAS_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: 5000
  CLIP_GRADIENTS:
    CLIP_TYPE: value
    CLIP_VALUE: 1.0
    ENABLED: False
    NORM_TYPE: 2.0
  GAMMA: 0.1
  IMS_PER_BATCH: 32
  LR_MULTIPLIER_OVERWRITE: []
  LR_SCHEDULER_NAME: WarmupCosineLR
  MAX_ITER: 450000
  MOMENTUM: 0.9
  NESTEROV: False
  OPTIMIZER: sgd
  REFERENCE_WORLD_SIZE: 8
  STEPS: (30000,)
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 1000
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: None
  WEIGHT_DECAY_EMBED: 0.0
  WEIGHT_DECAY_NORM: 0.0
TENSORBOARD:
  TEST_VIS_MAX_IMAGES: 16
  TRAIN_LOADER_VIS_MAX_IMAGES: 16
  TRAIN_LOADER_VIS_WRITE_PERIOD: 20
TEST:
  AUG:
    ENABLED: False
    FLIP: True
    MAX_SIZE: 4000
    MIN_SIZES: (400, 500, 600, 700, 800, 900, 1000, 1100, 1200)
  DETECTIONS_PER_IMAGE: 100
  EVAL_PERIOD: 5000
  EXPECTED_RESULTS: []
  KEYPOINT_OKS_SIGMAS: []
  PRECISE_BN:
    ENABLED: False
    NUM_ITER: 200
VERSION: 2
VIS_PERIOD: 0
[04/21 21:19:11 d2go.setup]: Running with runner: <d2go.runner.default_runner.GeneralizedRCNNRunner object at 0x7f8d80c45550>
[04/21 21:19:11 d2go.config.config]: Applying auto scaling method: default_scale_d2_configs
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/mobile_cv/common/misc/py.py", line 133, in new_func
    return func(*args, **kwargs)
  File "tools/train_net.py", line 34, in main
    setup_after_launch(cfg, output_dir, runner)
  File "/workspace/d2go/d2go/setup.py", line 213, in setup_after_launch
    auto_scale_world_size(cfg, new_world_size=comm.get_world_size())
  File "/workspace/d2go/d2go/config/config.py", line 155, in auto_scale_world_size
    CONFIG_SCALING_METHOD_REGISTRY.get(scaling_method)(cfg, new_world_size)
  File "/workspace/d2go/d2go/runner/default_runner.py", line 96, in default_scale_d2_configs
    base_lr_end = cfg.SOLVER.BASE_LR_END
  File "/opt/conda/lib/python3.7/site-packages/yacs/config.py", line 141, in __getattr__
    raise AttributeError(name)
AttributeError: BASE_LR_END
> /opt/conda/lib/python3.7/site-packages/yacs/config.py(141)__getattr__()
-> raise AttributeError(name)
(Pdb)
```

6. please simplify the steps as much as possible so they do not require additional resources to run, such as a private dataset.

I used docker with `pytorch:1.10.0-cuda11.3-cudnn8-devel` as a development base. Then pip-installed opencv-python and detectron2 (`detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu111/torch1.10/index.html`) as well as mobile-vision (`git+https://github.com/facebookresearch/mobile-vision.git`).
Finally, git-cloned this repo and ran `pip install -e .` from the root.

I can provide a pip freeze if necessary.

## Expected behavior:

Training process starts.

**Comment by akiross** [comment]
Fixed installing d2 from sources. Closing.
