### ISSUE TITLE
Fail to implement the quantization-aware training of demo 

### ISSUE THREAD

**Issue by chiehpower** [facebookresearch/d2go#32]
## Instructions To Reproduce the 🐛 Bug:

I already made sure that d2go could train with custom datasets and predict. 
I wanna use the quantization-aware-training this function by d2go.

1. Run the command from [Getting Started with D2Go](https://github.com/facebookresearch/d2go/tree/master/demo#quantization-aware-training)

I added a part for registering custom dataset in `train_net.py`

 ```python
    from detectron2.data import MetadataCatalog, DatasetCatalog
    from detectron2.data.datasets import register_coco_instances

    register_coco_instances("my_dataset_train", {}, "datasets/train_Images/trainval_area.json", "datasets/train_Images/")
    register_coco_instances("my_dataset_val", {}, "datasets/test_Images/testval_area.json", "datasets/test_Images/")

    my_dataset_train_metadata = MetadataCatalog.get("my_dataset_train")
    dataset_dicts = DatasetCatalog.get("my_dataset_train")

    my_dataset_val_metadata = MetadataCatalog.get("my_dataset_val")
    val_dataset_dicts = DatasetCatalog.get("my_dataset_val")

    for dd in ["my_dataset_train", "my_dataset_val"]:
        MetadataCatalog.get(dd).set(thing_classes=['top', 'bottom', 'top_ov', 'bottom_ov'])
 ```

Also, added the num_class parameter before `setup_after_launch()`

```python
    cfg.defrost()
    cfg.MODEL.ROI_HEADS.NUM_CLASSES = 4
    cfg.freeze()
```

Add the dataset in `qat_faster_rcnn_fbnetv3a_C4.yaml` file

```yaml
DATASETS:
  TRAIN: ("my_dataset_train",)
  TEST: ("my_dataset_val",)
```

**Command:**

```
$ python3 tools/train_net.py --config-file configs/qat_faster_rcnn_fbnetv3a_C4.yaml
MODEL.WEIGHTS model_0479999.pth
```

I encountered this error messages below:

**Output:**

```
[03/29 10:34:36 d2go.modeling.model_ema]: Using Model EMA.
Traceback (most recent call last):
  File "/home/chieh/.local/lib/python3.6/site-packages/mobile_cv/common/misc/py.py", line 122, in new_func
    return func(*args, **kwargs)
  File "tools/train_net.py", line 39, in main
    model = runner.build_model(cfg)
  File "/home/chieh/.local/lib/python3.6/site-packages/d2go/runner/default_runner.py", line 251, in build_model
    cfg, model, enable_fake_quant=eval_only, enable_observer=False
  File "/home/chieh/.local/lib/python3.6/site-packages/d2go/modeling/quantization.py", line 217, in wrapper
    return quant_func(cfg, model, *args, **kwargs)
  File "/home/chieh/.local/lib/python3.6/site-packages/d2go/modeling/quantization.py", line 336, in setup_qat_model
    model = model.prepare_for_quant(cfg)
  File "/home/chieh/.local/lib/python3.6/site-packages/d2go/export/d2_meta_arch.py", line 117, in d2_meta_arch_prepare_for_quant
    model = fuse_utils.fuse_model(model, inplace=True)
  File "/home/chieh/.local/lib/python3.6/site-packages/mobile_cv/arch/utils/fuse_utils.py", line 162, in fuse_model
    return fuse_model_inplace(model)
  File "/home/chieh/.local/lib/python3.6/site-packages/mobile_cv/arch/utils/fuse_utils.py", line 155, in fuse_model_inplace
    children[name] = fuse_model_inplace(child)
  File "/home/chieh/.local/lib/python3.6/site-packages/mobile_cv/arch/utils/fuse_utils.py", line 155, in fuse_model_inplace
    children[name] = fuse_model_inplace(child)
  File "/home/chieh/.local/lib/python3.6/site-packages/mobile_cv/arch/utils/fuse_utils.py", line 155, in fuse_model_inplace
    children[name] = fuse_model_inplace(child)
  [Previous line repeated 1 more time]
  File "/home/chieh/.local/lib/python3.6/site-packages/mobile_cv/arch/utils/fuse_utils.py", line 152, in fuse_model_inplace
    model = fuse_convbnrelu(model, inplace=True)
  File "/home/chieh/.local/lib/python3.6/site-packages/mobile_cv/arch/utils/fuse_utils.py", line 146, in fuse_convbnrelu
    ret, fuse_names, inplace=True, fuser_func=fuse_more_modules
  File "/usr/local/lib/python3.6/dist-packages/torch/quantization/fuse_modules.py", line 131, in fuse_modules
    _fuse_modules(model, module_list, fuser_func)
  File "/usr/local/lib/python3.6/dist-packages/torch/quantization/fuse_modules.py", line 74, in _fuse_modules
    new_mod_list = fuser_func(mod_list)
  File "/home/chieh/.local/lib/python3.6/site-packages/mobile_cv/arch/utils/fuse_utils.py", line 95, in fuse_more_modules
    return fuse_known_modules(mod_list)
  File "/usr/local/lib/python3.6/dist-packages/torch/quantization/fuse_modules.py", line 46, in fuse_known_modules
    raise NotImplementedError("Cannot fuse modules: {}".format(types))
NotImplementedError: Cannot fuse modules: (<class 'torch.nn.modules.conv.Conv2d'>, <class 'mobile_cv.arch.layers.batch_norm.NaiveSyncBatchNorm'>, <class 'torch.nn.modules.activation.ReLU'>)
> /usr/local/lib/python3.6/dist-packages/torch/quantization/fuse_modules.py(46)fuse_known_modules()
-> raise NotImplementedError("Cannot fuse modules: {}".format(types))
```

2. What exact command you run:

```
python3 tools/train_net.py --config-file configs/qat_faster_rcnn_fbnetv3a_C4.yaml MODEL.WEIGHTS model_0479999.pth  
```

3. Here is my full logs:
[log.txt](https://github.com/facebookresearch/d2go/files/6218881/log.txt)

4. Here is my config.yaml: (Because github cannot support yaml, I amended to txt file)
[config.txt](https://github.com/facebookresearch/d2go/files/6218893/config.txt)

## Expected behavior:

I wish I can implement the quantization-aware-training with custom dataset without any error.

Thank you!!

Best regards,
Chieh

**Comment by zhanghang1989** [comment]
Thanks for the feedback. Which PyTorch version you're using?

**Comment by chiehpower** [comment]
Hi @zhanghang1989 ,

Thanks for your reply!
My pytorch version is `1.7.1`.

Here is my detail environment information from `log.txt`.

```
sys.platform            linux
Python                  3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
numpy                   1.19.4
detectron2              0.4 @/home/chieh/.local/lib/python3.6/site-packages/detectron2
Compiler                GCC 7.3
CUDA compiler           CUDA 10.2
detectron2 arch flags   /home/chieh/.local/lib/python3.6/site-packages/detectron2/_C.cpython-36m-x86_64-linux-gnu.so; cannot find cuobjdump
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.7.1 @/usr/local/lib/python3.6/dist-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0                   TITAN V (arch=7.0)
CUDA_HOME               :/usr/local/cuda-10.2:/usr/local/cuda-10.2 - invalid!
Pillow                  8.1.0
torchvision             0.8.2 @/usr/local/lib/python3.6/dist-packages/torchvision
torchvision arch flags  /usr/local/lib/python3.6/dist-packages/torchvision/_C.so; cannot find cuobjdump
fvcore                  0.1.3.post20210311
cv2                     4.1.2
```

Thanks!

**Comment by zhanghang1989** [comment]
Could you try the latest version of PyTorch?  You may install it using the command https://github.com/facebookresearch/d2go#installation
