### ISSUE TITLE
AttributeError: 'GeneralizedRCNNRunner' object has no attribute 'from_config' and ModuleNotFoundError: No module named 'd2go.runner.callbacks 

### ISSUE THREAD

**Issue by Arvind-Ideas2IT** [facebookresearch/d2go#36]
Hi, Thanks for this cool project.

I went to through the notebook provided in the demo folder and was able to execute with no error. I am actually more interested to train the same balloon dataset with the  Pytorch lightning enabled script lightning_train_net.py  provided in the tools but faced  few errors as below
1. ModuleNotFoundError: No module named 'd2go.runner.callbacks, though everything is inlined.
2. AttributeError: 'GeneralizedRCNNRunner' object has no attribute 'from_config

As QuantizationAwareTraining was optional so I disabled it in the main function  as below 

cfg = build_config(args.config_file, task_cls, **opts=["QUANTIZATION.QAT.ENABLED",False**,"DATASETS.TRAIN" ,("balloon_train",), "DATASETS.TEST",("balloon_val",),"MODEL.DEVICE","cpu"]) 

but the object has no attribute 'from_config error still occurs, I have printed the attributes of  GeneralizedRCNNRunner and as I expected **from_config** attribute is not present. Though the strange thing is that I am able to call  **from_config**  methods in  lightning_task.py in the runner module from where we are importing  GeneralizedRCNNRunner object in  lightning_train_net.py

![image](https://user-images.githubusercontent.com/78946860/114162921-353f4a00-9947-11eb-9b18-1e2c03d62aa2.png)

![image](https://user-images.githubusercontent.com/78946860/114162490-c5c95a80-9946-11eb-825c-306b8786dc24.png)

## 
1.I have not made any changes in the lightning_train_net.py  just override few config parameters as you can see below
![image](https://user-images.githubusercontent.com/78946860/114163359-b5fe4600-9947-11eb-8a30-c20a3774e36c.png)
 and use  python lightning_train_net.py --config-file /home/arvind/d2go/configs/faster_rcnn_fbnetv3a_C4.yaml to run the training

3. __Full logs__ or other relevant observations:
```
(D2GO) arvind@arvind-ThinkPad-P14s-Gen-1:~/d2go/tools$ python lightning_train_net.py --config-file /home/arvind/d2go/configs/faster_rcnn_fbnetv3a_C4.yaml 
[INFO] Attributes for  GeneralizedRCNNTask ...  ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_create_after_step_hook', '_create_qat_hook', '_do_test', '_initialize', 'build_caffe2_model', 'build_checkpointer', 'build_detection_test_loader', 'build_detection_train_loader', 'build_lr_scheduler', 'build_model', 'build_optimizer', 'build_traceable_model', 'do_test', 'do_train', 'final_model_name', 'get_data_loader_vis_wrapper', 'get_default_cfg', 'get_evaluator', 'get_mapper', 'get_visualization_evaluator', 'register']
ABNORMAL_CHECKER:
  ENABLED: False
CUDNN_BENCHMARK: False
D2GO_DATA:
  AUG_OPS:
    TEST: ['ResizeShortestEdgeOp']
    TRAIN: ['ResizeShortestEdgeOp', 'RandomFlipOp']
  DATASETS:
    COCO_INJECTION:
      IM_DIRS: []
      JSON_FILES: []
      NAMES: []
    DYNAMIC_DATASETS: []
    TEST_CATEGORIES: ()
    TRAIN_CATEGORIES: ()
  MAPPER:
    BACKFILL_SIZE: False
    CATCH_EXCEPTION: True
    NAME: D2GoDatasetMapper
    RETRY: 3
  TEST:
    MAX_IMAGES: 0
    SUBSET_SAMPLING: frontmost
DATALOADER:
  ASPECT_RATIO_GROUPING: True
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4
  REPEAT_THRESHOLD: 0.0
  SAMPLER_TRAIN: TrainingSampler
DATASETS:
  PRECOMPUTED_PROPOSAL_TOPK_TEST: 1000
  PRECOMPUTED_PROPOSAL_TOPK_TRAIN: 2000
  PROPOSAL_FILES_TEST: ()
  PROPOSAL_FILES_TRAIN: ()
  TEST: ('balloon_val',)
  TRAIN: ('balloon_train',)
  TRAIN_REPEAT_FACTOR: []
EXPORT_CAFFE2:
  USE_HEATMAP_MAX_KEYPOINT: False
GLOBAL:
  HACK: 1.0
INPUT:
  CROP:
    ENABLED: False
    SIZE: [0.9, 0.9]
    TYPE: relative_range
  FORMAT: BGR
  MASK_FORMAT: polygon
  MAX_SIZE_TEST: 320
  MAX_SIZE_TRAIN: 320
  MIN_SIZE_TEST: 224
  MIN_SIZE_TRAIN: (224,)
  MIN_SIZE_TRAIN_SAMPLING: choice
  RANDOM_FLIP: horizontal
MODEL:
  ANCHOR_GENERATOR:
    ANGLES: [[-90, 0, 90]]
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]
    NAME: DefaultAnchorGenerator
    OFFSET: 0.0
    SIZES: [[32, 64, 96, 128, 160]]
  BACKBONE:
    FREEZE_AT: 2
    NAME: FBNetV2C4Backbone
  DDP_FIND_UNUSED_PARAMETERS: False
  DEVICE: cpu
  FBNET_V2:
    ARCH: FBNetV3_A
    ARCH_DEF: []
    NORM: naiveSyncBN
    NORM_ARGS: []
    SCALE_FACTOR: 1.0
    STEM_IN_CHANNELS: 3
    WIDTH_DIVISOR: 8
  FPN:
    FUSE_TYPE: sum
    IN_FEATURES: []
    NORM: 
    OUT_CHANNELS: 256
  FROZEN_LAYER_REG_EXP: []
  KEYPOINT_ON: False
  KMEANS_ANCHORS:
    DATASETS: ()
    KMEANS_ANCHORS_ON: False
    NUM_CLUSTERS: 0
    NUM_TRAINING_IMG: 0
    RNG_SEED: 3
  LOAD_PROPOSALS: False
  MASK_ON: False
  META_ARCHITECTURE: GeneralizedRCNN
  PANOPTIC_FPN:
    COMBINE:
      ENABLED: True
      INSTANCES_CONFIDENCE_THRESH: 0.5
      OVERLAP_THRESH: 0.5
      STUFF_AREA_LIMIT: 4096
    INSTANCE_LOSS_WEIGHT: 1.0
  PIXEL_MEAN: [103.53, 116.28, 123.675]
  PIXEL_STD: [1.0, 1.0, 1.0]
  PROPOSAL_GENERATOR:
    MIN_SIZE: 0
    NAME: RPN
  RESNETS:
    DEFORM_MODULATED: False
    DEFORM_NUM_GROUPS: 1
    DEFORM_ON_PER_STAGE: [False, False, False, False]
    DEPTH: 50
    NORM: FrozenBN
    NUM_GROUPS: 1
    OUT_FEATURES: ['res4']
    RES2_OUT_CHANNELS: 256
    RES5_DILATION: 1
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: True
    WIDTH_PER_GROUP: 64
  RETINANET:
    BBOX_REG_LOSS_TYPE: smooth_l1
    BBOX_REG_WEIGHTS: (1.0, 1.0, 1.0, 1.0)
    FOCAL_LOSS_ALPHA: 0.25
    FOCAL_LOSS_GAMMA: 2.0
    IN_FEATURES: ['p3', 'p4', 'p5', 'p6', 'p7']
    IOU_LABELS: [0, -1, 1]
    IOU_THRESHOLDS: [0.4, 0.5]
    NMS_THRESH_TEST: 0.5
    NORM: 
    NUM_CLASSES: 80
    NUM_CONVS: 4
    PRIOR_PROB: 0.01
    SCORE_THRESH_TEST: 0.05
    SMOOTH_L1_LOSS_BETA: 0.1
    TOPK_CANDIDATES_TEST: 1000
  ROI_BOX_CASCADE_HEAD:
    BBOX_REG_WEIGHTS: ((10.0, 10.0, 5.0, 5.0), (20.0, 20.0, 10.0, 10.0), (30.0, 30.0, 15.0, 15.0))
    IOUS: (0.5, 0.6, 0.7)
  ROI_BOX_HEAD:
    BBOX_REG_LOSS_TYPE: smooth_l1
    BBOX_REG_LOSS_WEIGHT: 1.0
    BBOX_REG_WEIGHTS: (10.0, 10.0, 5.0, 5.0)
    CLS_AGNOSTIC_BBOX_REG: False
    CONV_DIM: 256
    FC_DIM: 1024
    NAME: FBNetV2RoIBoxHead
    NORM: naiveSyncBN
    NUM_CONV: 0
    NUM_FC: 0
    POOLER_RESOLUTION: 6
    POOLER_SAMPLING_RATIO: 0
    POOLER_TYPE: ROIAlignV2
    SMOOTH_L1_BETA: 0.0
    TRAIN_ON_PRED_BOXES: False
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 512
    IN_FEATURES: ['trunk3']
    IOU_LABELS: [0, 1]
    IOU_THRESHOLDS: [0.5]
    NAME: StandardROIHeads
    NMS_THRESH_TEST: 0.5
    NUM_CLASSES: 80
    POSITIVE_FRACTION: 0.25
    PROPOSAL_APPEND_GT: True
    SCORE_THRESH_TEST: 0.05
  ROI_KEYPOINT_HEAD:
    CONV_DIMS: (512, 512, 512, 512, 512, 512, 512, 512)
    LOSS_WEIGHT: 1.0
    MIN_KEYPOINTS_PER_IMAGE: 1
    NAME: KRCNNConvDeconvUpsampleHead
    NORMALIZE_LOSS_BY_VISIBLE_KEYPOINTS: True
    NUM_KEYPOINTS: 17
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_TYPE: ROIAlignV2
  ROI_MASK_HEAD:
    CLS_AGNOSTIC_MASK: False
    CONV_DIM: 256
    NAME: MaskRCNNConvUpsampleHead
    NORM: 
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_TYPE: ROIAlignV2
  RPN:
    BATCH_SIZE_PER_IMAGE: 256
    BBOX_REG_LOSS_TYPE: smooth_l1
    BBOX_REG_LOSS_WEIGHT: 1.0
    BBOX_REG_WEIGHTS: (1.0, 1.0, 1.0, 1.0)
    BOUNDARY_THRESH: -1
    CONV_DIMS: [-1]
    HEAD_NAME: FBNetV2RpnHead
    IN_FEATURES: ['trunk3']
    IOU_LABELS: [0, -1, 1]
    IOU_THRESHOLDS: [0.3, 0.7]
    LOSS_WEIGHT: 1.0
    NMS_THRESH: 0.7
    POSITIVE_FRACTION: 0.5
    POST_NMS_TOPK_TEST: 30
    POST_NMS_TOPK_TRAIN: 2000
    PRE_NMS_TOPK_TEST: 1000
    PRE_NMS_TOPK_TRAIN: 2000
    SMOOTH_L1_BETA: 0.0
  SEM_SEG_HEAD:
    COMMON_STRIDE: 4
    CONVS_DIM: 128
    IGNORE_VALUE: 255
    IN_FEATURES: ['p2', 'p3', 'p4', 'p5']
    LOSS_WEIGHT: 1.0
    NAME: SemSegFPNHead
    NORM: GN
    NUM_CLASSES: 54
  SUBCLASS:
    NUM_LAYERS: 1
    NUM_SUBCLASSES: 0
    SUBCLASS_ID_FETCHER: SubclassFetcher
    SUBCLASS_MAPPING: []
    SUBCLASS_ON: False
  VT_FPN:
    HEADS: 16
    IN_FEATURES: ['res2', 'res3', 'res4', 'res5']
    LAYERS: 3
    MIN_GROUP_PLANES: 64
    NORM: BN
    OUT_CHANNELS: 256
    POS_HWS: []
    POS_N_DOWNSAMPLE: []
    TOKEN_C: 1024
    TOKEN_LS: [16, 16, 8, 8]
  WEIGHTS: 
MODEL_EMA:
  DECAY: 0.9998
  DEVICE: 
  ENABLED: True
  USE_EMA_WEIGHTS_FOR_EVAL_ONLY: False
OUTPUT_DIR: ./output
QUANTIZATION:
  BACKEND: fbgemm
  CUSTOM_QSCHEME: 
  EAGER_MODE: True
  PTQ:
    CALIBRATION_FORCE_ON_GPU: False
    CALIBRATION_NUM_IMAGES: 1
  QAT:
    BATCH_SIZE_FACTOR: 1.0
    DISABLE_OBSERVER_ITER: 38000
    ENABLED: False
    ENABLE_OBSERVER_ITER: 35000
    FREEZE_BN_ITER: 37000
    START_ITER: 35000
    UPDATE_OBSERVER_STATS_PERIOD: 1
    UPDATE_OBSERVER_STATS_PERIODICALLY: False
  SILICON_QAT:
    ENABLED: False
SEED: -1
SOLVER:
  AMP:
    ENABLED: False
  AUTO_SCALING_METHODS: ['default_scale_d2_configs', 'default_scale_quantization_configs']
  BASE_LR: 0.16
  BIAS_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: 5000
  CLIP_GRADIENTS:
    CLIP_TYPE: value
    CLIP_VALUE: 1.0
    ENABLED: False
    NORM_TYPE: 2.0
  GAMMA: 0.1
  IMS_PER_BATCH: 32
  LR_MULTIPLIER_OVERWRITE: []
  LR_SCHEDULER_NAME: WarmupCosineLR
  MAX_ITER: 540000
  MOMENTUM: 0.9
  NESTEROV: False
  OPTIMIZER: sgd
  REFERENCE_WORLD_SIZE: 8
  STEPS: (60000, 80000)
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 1000
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0.0001
  WEIGHT_DECAY_NORM: 0.0
TENSORBOARD:
  TEST_VIS_MAX_IMAGES: 16
  TRAIN_LOADER_VIS_MAX_IMAGES: 16
  TRAIN_LOADER_VIS_WRITE_PERIOD: 20
TEST:
  AUG:
    ENABLED: False
    FLIP: True
    MAX_SIZE: 4000
    MIN_SIZES: (400, 500, 600, 700, 800, 900, 1000, 1100, 1200)
  DETECTIONS_PER_IMAGE: 100
  EVAL_PERIOD: 10000
  EXPECTED_RESULTS: []
  KEYPOINT_OKS_SIGMAS: []
  PRECISE_BN:
    ENABLED: False
    NUM_ITER: 200
VERSION: 2
VIS_PERIOD: 0
[INFO] we are reached here......
Traceback (most recent call last):
  File "lightning_train_net.py", line 261, in <module>
    ret = main(
  File "lightning_train_net.py", line 185, in main
    task = task_cls.from_config(cfg, eval_only)
AttributeError: 'GeneralizedRCNNRunner' object has no attribute 'from_config'


I have followed the exact steps mentioned in the repo to build d2go. Please let me know if any other information needed. It would be a great help if you guys tell me what I am missing?

Thanks

**Comment by austinmw** [comment]
I just recently got this error. Any solution found?
