### ISSUE TITLE
AssertionError when trying to export faster_rcnn_fbnetv3g_fpn.yaml 

### ISSUE THREAD

**Issue by hiivin** [facebookresearch/d2go#39]
## Instructions To Reproduce the 🐛 Bug:
1. Full runnable code or full changes you made:
```
import copy
from detectron2.data import build_detection_test_loader
from d2go.export.api import convert_and_export_predictor
from d2go.utils.testing.data_loader_helper import create_fake_detection_data_loader
from d2go.export.d2_meta_arch import patch_d2_meta_arch
from d2go.model_zoo import model_zoo

import logging

# disable all the warnings
previous_level = logging.root.manager.disable
logging.disable(logging.INFO)

patch_d2_meta_arch()

cfg_name = 'faster_rcnn_fbnetv3g_fpn.yaml'
pytorch_model = model_zoo.get(cfg_name, trained=True)
pytorch_model.cpu()

with create_fake_detection_data_loader(224, 320, is_train=False) as data_loader:
    predictor_path = convert_and_export_predictor(
            model_zoo.get_config(cfg_name),
            copy.deepcopy(pytorch_model),
            "torchscript_int8@tracing",
            './',
            data_loader,
        )

# recover the logging level
logging.disable(previous_level)
```
2. What exact command you run: `python export_test.py`
3. __Full logs__ or other relevant observations:
```
Arguments ['width_divisor', 'dw_skip_bnrelu', 'zero_last_bn_gamma'] skipped for op Conv2d
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
/home/florian/anaconda3/envs/d2go1.8.1/lib/python3.8/site-packages/torch/quantization/observer.py:121: UserWarning: Please use quant_min and quant_max to specify the range for observers.                     reduce_range will be deprecated in a future release of PyTorch.
  warnings.warn(
Traceback (most recent call last):
  File "d2go/export_test.py", line 21, in <module>
    predictor_path = convert_and_export_predictor(
  File "/home/florian/Documents/Repositories/pytorch_source/d2go/d2go/export/api.py", line 100, in convert_and_export_predictor
    assert not fuse_utils.check_bn_exist(pytorch_model)
AssertionError
```
4. please simplify the steps as much as possible so they do not require additional resources to run, such as a private dataset.

## Expected behavior:

I used the sample code from the d2go_beginner notebook and changed faster_rcnn_fbnetv3a_dsmask_C4.yaml to faster_rcnn_fbnetv3g_fpn.yaml, but this seems to break the export functionality and I receive the AssertionError.

**Comment by zhanghang1989** [comment]
Could you change the all `NORM: "naiveSyncBN"` to `NORM: "bn"` and try again?

**Comment by hiivin** [comment]
> Could you change the all `NORM: "naiveSyncBN"` to `NORM: "bn"` in the config file and try again?

Sure, but when I replace it with lowercase "bn" and build d2go again, I receive the following error:
```
Arguments ['width_divisor', 'dw_skip_bnrelu', 'zero_last_bn_gamma'] skipped for op Conv2d
Traceback (most recent call last):
  File "export_test.py", line 18, in <module>
    pytorch_model = model_zoo.get(cfg_name, trained=True)
  File "/home/florian/Documents/Repositories/d2go/d2go/model_zoo/model_zoo.py", line 102, in get
    model = runner.build_model(cfg)
  File "/home/florian/Documents/Repositories/d2go/d2go/runner/default_runner.py", line 244, in build_model
    model = build_model(cfg)
  File "/home/florian/anaconda3/envs/d2goTest/lib/python3.8/site-packages/detectron2/modeling/meta_arch/build.py", line 21, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "/home/florian/anaconda3/envs/d2goTest/lib/python3.8/site-packages/detectron2/config/config.py", line 181, in wrapped
    explicit_args = _get_args_from_config(from_config_func, *args, **kwargs)
  File "/home/florian/anaconda3/envs/d2goTest/lib/python3.8/site-packages/detectron2/config/config.py", line 238, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "/home/florian/anaconda3/envs/d2goTest/lib/python3.8/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 75, in from_config
    backbone = build_backbone(cfg)
  File "/home/florian/anaconda3/envs/d2goTest/lib/python3.8/site-packages/detectron2/modeling/backbone/build.py", line 31, in build_backbone
    backbone = BACKBONE_REGISTRY.get(backbone_name)(cfg, input_shape)
  File "/home/florian/Documents/Repositories/d2go/d2go/modeling/backbone/fbnet_v2.py", line 298, in FBNetV2FpnBackbone
    backbone = FBNetV2FPN(
  File "/home/florian/anaconda3/envs/d2goTest/lib/python3.8/site-packages/detectron2/modeling/backbone/fpn.py", line 66, in __init__
    lateral_norm = get_norm(norm, out_channels)
  File "/home/florian/anaconda3/envs/d2goTest/lib/python3.8/site-packages/detectron2/layers/batch_norm.py", line 146, in get_norm
    norm = {
KeyError: 'bn'
```

I also tried uppercase "BN":

```
Arguments ['width_divisor', 'dw_skip_bnrelu', 'zero_last_bn_gamma'] skipped for op Conv2d
Traceback (most recent call last):
  File "export_test.py", line 18, in <module>
    pytorch_model = model_zoo.get(cfg_name, trained=True)
  File "/home/florian/Documents/Repositories/d2go/d2go/model_zoo/model_zoo.py", line 102, in get
    model = runner.build_model(cfg)
  File "/home/florian/Documents/Repositories/d2go/d2go/runner/default_runner.py", line 244, in build_model
    model = build_model(cfg)
  File "/home/florian/anaconda3/envs/d2goTest/lib/python3.8/site-packages/detectron2/modeling/meta_arch/build.py", line 21, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "/home/florian/anaconda3/envs/d2goTest/lib/python3.8/site-packages/detectron2/config/config.py", line 181, in wrapped
    explicit_args = _get_args_from_config(from_config_func, *args, **kwargs)
  File "/home/florian/anaconda3/envs/d2goTest/lib/python3.8/site-packages/detectron2/config/config.py", line 238, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "/home/florian/anaconda3/envs/d2goTest/lib/python3.8/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 75, in from_config
    backbone = build_backbone(cfg)
  File "/home/florian/anaconda3/envs/d2goTest/lib/python3.8/site-packages/detectron2/modeling/backbone/build.py", line 31, in build_backbone
    backbone = BACKBONE_REGISTRY.get(backbone_name)(cfg, input_shape)
  File "/home/florian/Documents/Repositories/d2go/d2go/modeling/backbone/fbnet_v2.py", line 299, in FBNetV2FpnBackbone
    bottom_up=build_fbnet_backbone(cfg),
  File "/home/florian/Documents/Repositories/d2go/d2go/modeling/backbone/fbnet_v2.py", line 280, in build_fbnet_backbone
    return FBNetV2Backbone(cfg)
  File "/home/florian/Documents/Repositories/d2go/d2go/modeling/backbone/fbnet_v2.py", line 228, in __init__
    stages, shape_specs = build_fbnet(
  File "/home/florian/Documents/Repositories/d2go/d2go/modeling/backbone/fbnet_v2.py", line 195, in build_fbnet
    stages.append(builder.build_blocks(
  File "/home/florian/anaconda3/envs/d2goTest/lib/python3.8/site-packages/mobile_cv/arch/fbnet_v2/fbnet_builder.py", line 503, in build_blocks
    nnblock = self.build_block(
  File "/home/florian/anaconda3/envs/d2goTest/lib/python3.8/site-packages/mobile_cv/arch/fbnet_v2/fbnet_builder.py", line 537, in build_block
    ret = PRIMITIVES.get(block_op)(in_channels, out_channels, **new_kwargs)
  File "/home/florian/anaconda3/envs/d2goTest/lib/python3.8/site-packages/mobile_cv/arch/fbnet_v2/blocks_factory.py", line 51, in <lambda>
    "conv_k3": lambda in_channels, out_channels, stride, **kwargs: bb.ConvBNRelu(
  File "/home/florian/anaconda3/envs/d2goTest/lib/python3.8/site-packages/mobile_cv/arch/fbnet_v2/basic_blocks.py", line 419, in __init__
    build_bn(num_channels=out_channels, **hp.unify_args(bn_args))
  File "/home/florian/anaconda3/envs/d2goTest/lib/python3.8/site-packages/mobile_cv/arch/fbnet_v2/basic_blocks.py", line 322, in build_bn
    return BN_REGISTRY.get(name)(num_channels, zero_gamma=zero_gamma, **kwargs)
  File "/home/florian/anaconda3/envs/d2goTest/lib/python3.8/site-packages/mobile_cv/common/misc/registry.py", line 73, in get
    raise KeyError(
KeyError: "No object named 'BN' found in 'bn' registry! Available names: []"
```

**Comment by petoor** [comment]
Removing norm from the config i can convert both torchscript_int8 and torchscript. The performance seems to be okay but definitely needs more testing since removing the norm will have an impact. 
NB. I tested with faster_rcnn_fbnetv3a_C4.yaml but it should also work for the 3g model.

**Comment by zhanghang1989** [comment]
Could you add / change the following in the config file when exporting int8 model?
```
QUANTIZATION:
  BACKEND: "qnnpack"
```
Similar to this one:
https://github.com/facebookresearch/d2go/blob/master/configs/qat_faster_rcnn_fbnetv3a_C4.yaml#L6-L7

**Comment by zhanghang1989** [comment]
> I have tried various different configs now and the addition of
> 
> ```
> QUANTIZATION:
>   BACKEND: "qnnpack"
> ```
> 
> leads to the same AssertionError.

Are you using the latest code? I thought this issue has been resolved.

**Comment by hiivin** [comment]
Yes, I just removed d2go and reinstalled it from a fresh clone to double check. The issue should be quite easy to reproduce with the code I provided.

**Comment by johnahjohn** [comment]
i am not able to get the simplified model weights for faster_rcnn_fbnetv3g_fpn.yaml
I had made some changes to the code according to the above comments to make it work without errors.
1. cfg.MODEL.FBNET_V2.NORM = None
2. Changing cfg.MODEL.FBNET_V2.NORM from  NORM: "naiveSyncBN" to NORM: "bn"
But still its showing assertion error.
how to resolve these errors.
